<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE translation2 [
<!ELEMENT translation2 (languages,pages)>
<!ELEMENT languages (lang*)>
<!ELEMENT lang (#PCDATA)>
<!ATTLIST lang id ID #REQUIRED>
<!ELEMENT pages (page*)>
<!ELEMENT page (string*)>
<!ATTLIST page key CDATA #REQUIRED>
<!ELEMENT string (tr*)>
<!ATTLIST string key CDATA #REQUIRED>
<!ELEMENT tr (#PCDATA)>
<!ATTLIST tr lang IDREF #REQUIRED>
]>

<translation2>
  <languages>
    <lang id="de"/>
  </languages>
  <pages>
    <page key="Frontend">
      <string key="City is not set">
        <tr lang="de">  </tr>
      </string>
      <string key="ZIP code is not set">
        <tr lang="de">  </tr>
      </string>
      <string key="Billing address is not set">
        <tr lang="de">  </tr>
      </string>
      <string key="CSC value is not set">
        <tr lang="de">  </tr>
      </string>
      <string key="Credit card number is not set">
        <tr lang="de">  </tr>
      </string>
      <string key="User last name is not set">
        <tr lang="de">  </tr>
      </string>
      <string key="Expiration year is not set">
        <tr lang="de">  </tr>
      </string>
      <string key="Expiration month is not set">
        <tr lang="de">  </tr>
      </string>
      <string key="User name is not set">
        <tr lang="de">  </tr>
      </string>
      <string key="Applications">
        <tr lang="de"> Bewerbungen </tr>
      </string>
      <string key="Job Search">
        <tr lang="de"> Job Suche </tr>
      </string>
      <string key="Find">
        <tr lang="de"> Finden </tr>
      </string>
      <string key="Advanced search">
        <tr lang="de"> Erweiterte Suche </tr>
      </string>
      <string key="Home">
        <tr lang="de"> Home </tr>
      </string>
      <string key="Register">
        <tr lang="de"> Registrieren </tr>
      </string>
      <string key="Sign In">
        <tr lang="de"> Einloggen </tr>
      </string>
      <string key="My Account">
        <tr lang="de"> Mein Account </tr>
      </string>
      <string key="Find Jobs">
        <tr lang="de"> Jobs finden </tr>
      </string>
      <string key="Post Resumes">
        <tr lang="de"> CV/Lebenslauf veröffentlichen </tr>
      </string>
      <string key="Search Resumes">
        <tr lang="de"> CV/Lebenslauf suchen </tr>
      </string>
      <string key="Post Jobs">
        <tr lang="de"> Job anbieten </tr>
      </string>
      <string key="Contact">
        <tr lang="de"> Kontakt </tr>
      </string>
      <string key="Choose language">
        <tr lang="de"> Sprache wählen </tr>
      </string>
      <string key="Jobs by Category">
        <tr lang="de"> Jobs nach Kategorie </tr>
      </string>
      <string key="Jobs by City">
        <tr lang="de"> Jobs nach Lage </tr>
      </string>
      <string key="Featured Jobs">
        <tr lang="de"> Featured Jobs </tr>
      </string>
      <string key="Employers">
        <tr lang="de"> Arbeitgeber </tr>
      </string>
      <string key="Search resumes">
        <tr lang="de"> Lebensläufe durchsuchen </tr>
      </string>
      <string key="Job Seekers">
        <tr lang="de"> Arbeitsuchende </tr>
      </string>
      <string key="Post resumes">
        <tr lang="de"> Lebensläufe veröffentlichen </tr>
      </string>
      <string key="Find jobs">
        <tr lang="de"> Jobs finden </tr>
      </string>
      <string key="RSS Feed">
        <tr lang="de"> RSS Feed </tr>
      </string>
      <string key="Latest Jobs">
        <tr lang="de"> Neueste Jobangebote </tr>
      </string>
      <string key="Keep me signed in">
        <tr lang="de"> Eingeloggt bleiben </tr>
      </string>
      <string key="Login">
        <tr lang="de"> Login </tr>
      </string>
      <string key="Forgot Your Password?">
        <tr lang="de"> Passwort vergessen? </tr>
      </string>
      <string key="Registration">
        <tr lang="de"> Registrierung </tr>
      </string>
      <string key="Salutation First and Last Name">
        <tr lang="de"> Begrüßung + Vor- und Nachname </tr>
      </string>
      <string key="Email">
        <tr lang="de"> E-Mail </tr>
      </string>
      <string key="Comments">
        <tr lang="de"> Kommentare </tr>
      </string>
      <string key="Submit">
        <tr lang="de"> Einstellen </tr>
      </string>
      <string key="Please select the appropriate user group">
        <tr lang="de"> Bitte wählen Sie die passende User-Kategorie aus. </tr>
      </string>
      <string key="Confirm Password">
        <tr lang="de"> Passwort bestätigen </tr>
      </string>
      <string key="You have successfully registered in our site">
        <tr lang="de"> Sie haben sich erfolgreich für unsere Website angemeldet. Vielen Dank! </tr>
      </string>
      <string key="Add a New Listing">
        <tr lang="de"> Neuen Eintrag erstellen </tr>
      </string>
      <string key="You specified wrong username">
        <tr lang="de"> Bitte überprüfen Sie den Usernamen </tr>
      </string>
      <string key="Invalid payment ID is specified">
        <tr lang="de"> Ungültige Zahlungs-ID angegeben </tr>
      </string>
      <string key="Search">
        <tr lang="de"> Suche </tr>
      </string>
      <string key="My Jobs">
        <tr lang="de"> Meine Jobs </tr>
      </string>
      <string key="My Profile">
        <tr lang="de"> Mein Profil </tr>
      </string>
      <string key="Saved Searches">
        <tr lang="de"> Gespeicherte Suchanfragen </tr>
      </string>
      <string key="Saved Listings">
        <tr lang="de"> Gespeicherte Einträge / Angebote </tr>
      </string>
      <string key="My Notifications">
        <tr lang="de"> Meine Benachrichtigungen </tr>
      </string>
      <string key="Billing History">
        <tr lang="de"> Rechnungsgeschichte </tr>
      </string>
      <string key="Logout">
        <tr lang="de"> Ausloggen </tr>
      </string>
      <string key="My Listings">
        <tr lang="de"> Meine Einträge </tr>
      </string>
      <string key="Filter">
        <tr lang="de"> Filter </tr>
      </string>
      <string key="unlimited">
        <tr lang="de"> unbegrenzt </tr>
      </string>
      <string key="Next">
        <tr lang="de"> Nächste </tr>
      </string>
      <string key="Edit Listing">
        <tr lang="de"> Einträge bearbeiten </tr>
      </string>
      <string key="Upgrade to Featured">
        <tr lang="de"> Upgrade zu &apos;Featured&apos; </tr>
      </string>
      <string key="You have already subscribed">
        <tr lang="de"> Sie haben sich bereits angemeldet </tr>
      </string>
      <string key="No listings found.">
        <tr lang="de"> Keine Einträge gefunden. </tr>
      </string>
      <string key="Listing ID is not defined">
        <tr lang="de"> Eintrags-ID nicht angegeben </tr>
      </string>
      <string key="Save">
        <tr lang="de"> Speichern </tr>
      </string>
      <string key="Image format is not supported">
        <tr lang="de"> Bildformat wird nicht unterstützt </tr>
      </string>
      <string key="You have successfully changed your profile info!">
        <tr lang="de"> Sie haben Ihr Profil erfolgreich angepasst. </tr>
      </string>
      <string key="Delete">
        <tr lang="de"> Löschen </tr>
      </string>
      <string key="File deleted successfully">
        <tr lang="de"> Datei wurde gelöscht </tr>
      </string>
      <string key="Back to edit profile">
        <tr lang="de"> Zurück zu &apos;Profil bearbeiten&apos; </tr>
      </string>
      <string key="You have not saved any searches yet.">
        <tr lang="de"> Sie haben noch keine Suchen gespeichert. </tr>
      </string>
      <string key="ID">
        <tr lang="de"> ID </tr>
      </string>
      <string key="Period">
        <tr lang="de"> Zeitraum </tr>
      </string>
      <string key="State">
        <tr lang="de"> Staat </tr>
      </string>
      <string key="from">
        <tr lang="de"> von </tr>
      </string>
      <string key="to">
        <tr lang="de"> bis </tr>
      </string>
      <string key="Date">
        <tr lang="de"> Datum </tr>
      </string>
      <string key="Description">
        <tr lang="de"> Beschreibung </tr>
      </string>
      <string key="Amount">
        <tr lang="de"> Betrag </tr>
      </string>
      <string key="Action">
        <tr lang="de"> Tätigkeit </tr>
      </string>
      <string key="Total Amount">
        <tr lang="de"> Gesamtbetrag </tr>
      </string>
      <string key="There are no saved listings">
        <tr lang="de"> Keine gespeicherten Einträge </tr>
      </string>
      <string key="Notify on Listing Activation">
        <tr lang="de"> Nachricht senden bei Eintrags-Aktivierung </tr>
      </string>
      <string key="Modify search">
        <tr lang="de"> Suche anpassen </tr>
      </string>
      <string key="Saved jobs">
        <tr lang="de"> Gespeicherte Jobs </tr>
      </string>
      <string key="Saved searches">
        <tr lang="de"> Gespeicherte Suchanfragen </tr>
      </string>
      <string key="Number of jobs per page">
        <tr lang="de"> Anzahl von Jobs pro Seite </tr>
      </string>
      <string key="Previous">
        <tr lang="de"> Vorherige </tr>
      </string>
      <string key="Save Your Search">
        <tr lang="de"> Suche speichern </tr>
      </string>
      <string key="Search Name">
        <tr lang="de"> Name </tr>
      </string>
      <string key="Your search has been saved.">
        <tr lang="de"> Ihre Suche wurde gespeichert </tr>
      </string>
      <string key="You may close this window now.">
        <tr lang="de"> Sie können dieses Fenster jetzt schließen </tr>
      </string>
      <string key="Save ad">
        <tr lang="de"> Inserat speichern </tr>
      </string>
      <string key="View job details">
        <tr lang="de"> Jobdetails anzeigen </tr>
      </string>
      <string key="Please, Vote!">
        <tr lang="de"> Bitte stimmen Sie ab! </tr>
      </string>
      <string key="Watch a video">
        <tr lang="de"> Video anzeigen </tr>
      </string>
      <string key="Save this Job">
        <tr lang="de"> Diesen Job speichern </tr>
      </string>
      <string key="View Saved Jobs">
        <tr lang="de"> Gespeicherte Jobs anzeigen </tr>
      </string>
      <string key="Tell a Friend">
        <tr lang="de"> Einem Freund weitersagen </tr>
      </string>
      <string key="Print This Ad">
        <tr lang="de"> Inserat ausdrucken </tr>
      </string>
      <string key="Map View">
        <tr lang="de"> Kartenansicht </tr>
      </string>
      <string key="Back to Results">
        <tr lang="de"> Zurück zu Suchergebnissen </tr>
      </string>
      <string key="Modify Search">
        <tr lang="de"> Suche anpassen </tr>
      </string>
      <string key="Rate This Job">
        <tr lang="de"> Dieses Jobangebot werten </tr>
      </string>
      <string key="User Info">
        <tr lang="de"> Nutzerdaten </tr>
      </string>
      <string key="Video">
        <tr lang="de"> Video </tr>
      </string>
      <string key="Apply Now">
        <tr lang="de"> Jetzt bewerben </tr>
      </string>
      <string key="Location">
        <tr lang="de"> Ort </tr>
      </string>
      <string key="Please wait ...">
        <tr lang="de"> Bitte warten … </tr>
      </string>
      <string key="Add your comment">
        <tr lang="de"> Kommentar erstellen </tr>
      </string>
      <string key="Add">
        <tr lang="de"> Hinzufügen </tr>
      </string>
      <string key="View details">
        <tr lang="de"> Details anzeigen </tr>
      </string>
      <string key="Recommend">
        <tr lang="de"> Empfehlen </tr>
      </string>
      <string key="Your name">
        <tr lang="de"> Ihr Name </tr>
      </string>
      <string key="Send">
        <tr lang="de"> Abschicken </tr>
      </string>
      <string key="Cannot send letter">
        <tr lang="de"> Kann nicht gesendet werden </tr>
      </string>
      <string key="Company Info">
        <tr lang="de"> Firmendaten </tr>
      </string>
      <string key="You&apos;ve already voted">
        <tr lang="de"> Sie haben bereits abgestimmt </tr>
      </string>
      <string key="Author">
        <tr lang="de"> Autor </tr>
      </string>
      <string key="Your e-mail">
        <tr lang="de"> Ihre E-Mail-Adresse </tr>
      </string>
      <string key="Attach your resume">
        <tr lang="de"> Lebenslauf anhängen </tr>
      </string>
      <string key="Number of resumes per page">
        <tr lang="de"> Anzahl von Lebensläufen pro Seite </tr>
      </string>
      <string key="Add Pictures">
        <tr lang="de"> Bilder hinzufügen </tr>
      </string>
      <string key="is empty">
        <tr lang="de"> ist leer </tr>
      </string>
      <string key="is unknown">
        <tr lang="de"> ist unbekannt </tr>
      </string>
      <string key="Manage Listing">
        <tr lang="de"> Eintrag verwalten </tr>
      </string>
      <string key="Preview Listing">
        <tr lang="de"> Vorschau des Eintrags </tr>
      </string>
      <string key="Add Picture">
        <tr lang="de"> Bild hinzufügen </tr>
      </string>
      <string key="Caption">
        <tr lang="de"> Untertitel </tr>
      </string>
      <string key="Thumbnail">
        <tr lang="de"> Thumbnail </tr>
      </string>
      <string key="Actions">
        <tr lang="de"> Aktion </tr>
      </string>
      <string key="Are you sure?">
        <tr lang="de"> Sind Sie sicher? </tr>
      </string>
      <string key="Edit Picture">
        <tr lang="de"> Bild bearbeiten </tr>
      </string>
      <string key="Picture">
        <tr lang="de"> Bild </tr>
      </string>
      <string key="Please specify a valid email address.">
        <tr lang="de"> Bitte geben Sie eine gültige E-Mail-Adresse ein. </tr>
      </string>
      <string key="Please provide your full name.">
        <tr lang="de"> Bitte geben Sie Ihren vollen Namen ein. </tr>
      </string>
      <string key="Please include your comments.">
        <tr lang="de"> Wie können wir Ihnen weiterhelfen? </tr>
      </string>
      <string key="Thank you very much for your message. We will respond to you as soon as possible.">
        <tr lang="de"> Vielen Dank für Ihre Nachricht! Wir werden uns auf schnellstem Wege bei Ihnen melden. </tr>
      </string>
      <string key="Login error">
        <tr lang="de"> Fehler beim Einloggen </tr>
      </string>
      <string key="Browse by category">
        <tr lang="de"> Ordnen nach Kategorie </tr>
      </string>
      <string key="There are no listings with requested parameters in the system.">
        <tr lang="de"> Es wurden keine Einträge zu Ihren Angaben im System gefunden. </tr>
      </string>
      <string key="Browse by city">
        <tr lang="de"> Durchsuchen nach Stadt </tr>
      </string>
      <string key="My Resumes">
        <tr lang="de"> Meine Lebensläufe </tr>
      </string>
      <string key="Saved Jobs">
        <tr lang="de"> Gespeicherte Jobs </tr>
      </string>
      <string key="Job Alerts">
        <tr lang="de"> Job-Benachrichtigungen </tr>
      </string>
      <string key="$select_box_field_distance of Zip $input_text_field_location">
        <tr lang="de"> $select_box_field_distance of Zip $input_text_field_location </tr>
      </string>
      <string key="$input_text_field_from to $input_text_field_to">
        <tr lang="de"> $input_text_field_from to $input_text_field_to </tr>
      </string>
      <string key="not confirmed">
        <tr lang="de"> nicht bestätigt </tr>
      </string>
      <string key="this value is already used in the system">
        <tr lang="de"> dieser Wert wird im System bereits verwendet </tr>
      </string>
      <string key="Actions with Selected">
        <tr lang="de"> Aktionen mit Ausgewähltem </tr>
      </string>
      <string key="Number of listings per page">
        <tr lang="de"> Anzahl der Einträge pro Seite </tr>
      </string>
      <string key="Deactivate">
        <tr lang="de"> Deaktivieren </tr>
      </string>
      <string key="Activate">
        <tr lang="de"> Aktivieren </tr>
      </string>
      <string key="Your listing is successfully activated">
        <tr lang="de"> Ihr Eintrag wurde erfolgreich aktiviert. </tr>
      </string>
      <string key="Back to My Listings">
        <tr lang="de"> Zurück zu meinen Einträgen </tr>
      </string>
      <string key="Sort by">
        <tr lang="de"> Sortieren nach </tr>
      </string>
      <string key="Edit">
        <tr lang="de"> Bearbeiten </tr>
      </string>
      <string key="Jobs by $companyName">
        <tr lang="de"> Jobs von $companyName </tr>
      </string>
      <string key="View resume details">
        <tr lang="de"> Lebenslauf-Details anzeigen </tr>
      </string>
      <string key="All resumes by this user">
        <tr lang="de"> Alle Lebensläufe dieses Users </tr>
      </string>
      <string key="Rate This Resume">
        <tr lang="de"> Diesen Lebenslauf bewerten </tr>
      </string>
      <string key="View Saved Resumes">
        <tr lang="de"> Gespeicherte CVs anzeigen </tr>
      </string>
      <string key="Save this Resume">
        <tr lang="de"> Diesen Lebenslauf speichern </tr>
      </string>
      <string key="Resumes by $firstName $lastName">
        <tr lang="de"> CVs von $firstName $lastName </tr>
      </string>
      <string key="is not an integer value">
        <tr lang="de"> ist keine ganze Zahl </tr>
      </string>
      <string key="limit exceeded">
        <tr lang="de"> Limit überschritten </tr>
      </string>
      <string key="You don&apos;t have permissions to access this page.">
        <tr lang="de"> Sie haben keine Zugriffsberechtigung für diese Seite. </tr>
      </string>
      <string key="Your friend&apos;s name">
        <tr lang="de"> Name Ihres Bekannten </tr>
      </string>
      <string key="Your friend&apos;s e-mail address">
        <tr lang="de"> E-Mail-Adresse Ihres Bekannten </tr>
      </string>
      <string key="Dear customer!">
        <tr lang="de"> Sehr geehrter Kunde, </tr>
      </string>
      <string key="Please choose from the following payment methods:">
        <tr lang="de"> Bitte wählen Sie eine der folgenden Zahlungsweisen aus: </tr>
      </string>
      <string key="Wire Transfer">
        <tr lang="de"> Überweisung </tr>
      </string>
      <string key="Anonymous User Info">
        <tr lang="de"> Anonyme Nutzer-Informationen </tr>
      </string>
      <string key="Welcome">
        <tr lang="de"> Willkommen </tr>
      </string>
      <string key="Please log in to access this page. If you do not have an account, please">
        <tr lang="de"> Bitte loggen Sie sich ein, um auf diese Seite zugreifen zu können. Wenn Sie noch nicht registriert sind, bitte </tr>
      </string>
      <string key="Featured Companies">
        <tr lang="de"> Vorgestellte Firmen </tr>
      </string>
      <string key="Get Resumes by Email">
        <tr lang="de"> Lebensläufe per E-Mail erhalten </tr>
      </string>
      <string key="Get Jobs by Email">
        <tr lang="de"> Jobangebote per E-Mail erhalten </tr>
      </string>
      <string key="Confirm E-mail">
        <tr lang="de"> E-Mail-Adresse bestätigen </tr>
      </string>
      <string key="Reload Image">
        <tr lang="de"> Bild neu laden </tr>
      </string>
      <string key="Accept terms of use">
        <tr lang="de"> Nutzungsbedingungen akzeptieren </tr>
      </string>
      <string key="Read terms of use">
        <tr lang="de"> Nutzungsbedingungen lesen </tr>
      </string>
      <string key="Resume Alerts">
        <tr lang="de"> CV-Alarme (Benachrichtigungen) </tr>
      </string>
      <string key="Application Tracking">
        <tr lang="de"> Bewerbungen verfolgen </tr>
      </string>
      <string key="Resume Alert Name">
        <tr lang="de"> Name dieses CV-Alarms </tr>
      </string>
      <string key="Add new resume alert">
        <tr lang="de"> Neuen CV-Alarm erstellen </tr>
      </string>
      <string key="Disable">
        <tr lang="de"> Deaktivieren </tr>
      </string>
      <string key="Preview Search Results">
        <tr lang="de"> Vorschau der Suchergebnisse </tr>
      </string>
      <string key="Add resume alert">
        <tr lang="de"> CV-Alarm hinzufügen </tr>
      </string>
      <string key="Alert Name">
        <tr lang="de"> Name des Alarms </tr>
      </string>
      <string key="Job Title">
        <tr lang="de"> Jobtitel </tr>
      </string>
      <string key="Date Applied">
        <tr lang="de"> Datum der Bewerbung </tr>
      </string>
      <string key="Status">
        <tr lang="de"> Status </tr>
      </string>
      <string key="Attached Resume">
        <tr lang="de"> Angehängter Lebenslauf </tr>
      </string>
      <string key="Applicant’s Name">
        <tr lang="de"> Name des Bewerbers </tr>
      </string>
      <string key="View Attached File">
        <tr lang="de"> Angehängte Datei betrachten </tr>
      </string>
      <string key="Job Search Results">
        <tr lang="de"> Resultate der Job-Suche </tr>
      </string>
      <string key="Company Profile">
        <tr lang="de"> Firmenprofil </tr>
      </string>
      <string key="here">
        <tr lang="de"> hier klicken </tr>
      </string>
      <string key="to add a new listing.">
        <tr lang="de"> um einen neuen Eintrag zu erstellen. </tr>
      </string>
      <string key="Fields marked with an asterisk (">
        <tr lang="de"> Markierte Felder ( </tr>
      </string>
      <string key=") are mandatory">
        <tr lang="de"> ) sind Pflichtfelder </tr>
      </string>
      <string key="Please log in to place a listing. If you do not have an account, please">
        <tr lang="de"> Bitte loggen Sie sich ein um einen Eintrag zu erstellen. Falls Sie noch nicht Mitglied sind, bitte </tr>
      </string>
      <string key="within $radius $radius_search_unit of $location">
        <tr lang="de"> innerhalb von $radius $radius_search_unit um $location </tr>
      </string>
      <string key="Apply to job">
        <tr lang="de"> Auf Stelle bewerben </tr>
      </string>
      <string key="Cover letter (optional)">
        <tr lang="de"> Anschreiben (optional) </tr>
      </string>
      <string key="You applied successfully">
        <tr lang="de"> Sie haben sich erfolgreich beworben. </tr>
      </string>
      <string key="Please log in to place a new posting. If you do not have an account, please">
        <tr lang="de"> Bitte loggen Sie sich ein um einen Eintrag zu erstellen. Falls Sie noch kein Mitglied sind, bitte </tr>
      </string>
      <string key="Register.">
        <tr lang="de"> Registrieren </tr>
      </string>
      <string key="Search by Company">
        <tr lang="de"> Suche nach Firma </tr>
      </string>
      <string key="Clone">
        <tr lang="de"> Kopieren </tr>
      </string>
      <string key="My Job Preview">
        <tr lang="de"> Meine Job Vorschau </tr>
      </string>
      <string key="Click to select">
        <tr lang="de"> Klicken zum Auswählen </tr>
      </string>
      <string key="Redirect to this URL">
        <tr lang="de"> Zu dieser URL umleiten </tr>
      </string>
      <string key="Use the following format:">
        <tr lang="de"> Nutzen Sie folgendes Format: </tr>
      </string>
      <string key="Your changes were successfully saved">
        <tr lang="de"> Ihre Änderungen wurden erfolgreich gespeichert. </tr>
      </string>
      <string key="Manage Pictures">
        <tr lang="de"> Bilder verwalten </tr>
      </string>
      <string key="Clone Job">
        <tr lang="de"> Job kopieren </tr>
      </string>
      <string key="Company">
        <tr lang="de"> Firma </tr>
      </string>
      <string key="My Applications">
        <tr lang="de"> Meine Bewerbungen </tr>
      </string>
      <string key="Select your resume">
        <tr lang="de"> Ihre Bewerbung auswählen </tr>
      </string>
      <string key="My Postings">
        <tr lang="de"> Meine Einträge </tr>
      </string>
      <string key="Private messages">
        <tr lang="de"> Persönliche Nachrichten </tr>
      </string>
      <string key="Inbox">
        <tr lang="de"> Posteingang </tr>
      </string>
      <string key="Outbox">
        <tr lang="de"> Postausgang </tr>
      </string>
      <string key="Edit Saved Search">
        <tr lang="de"> Abgespeicherte Suche bearbeiten </tr>
      </string>
      <string key="Saved Searches Name">
        <tr lang="de"> Name der abgespeicherten Suchanfragen </tr>
      </string>
      <string key="Notify on Jobs Expiration">
        <tr lang="de"> Nachricht senden, wenn Jobs verfallen </tr>
      </string>
      <string key="Cover Letter">
        <tr lang="de"> Anschreiben </tr>
      </string>
      <string key="Compose Message">
        <tr lang="de"> Nachricht verfassen </tr>
      </string>
      <string key="From">
        <tr lang="de"> Von </tr>
      </string>
      <string key="Subject">
        <tr lang="de"> Betreff </tr>
      </string>
      <string key="To">
        <tr lang="de"> an </tr>
      </string>
      <string key="Message to">
        <tr lang="de"> Nachricht an </tr>
      </string>
      <string key="Message">
        <tr lang="de"> Nachricht </tr>
      </string>
      <string key="Save to outbox">
        <tr lang="de"> In Postausgang speichern </tr>
      </string>
      <string key="Send private message">
        <tr lang="de"> Persönliche nachricht schicken </tr>
      </string>
      <string key="You&apos;re not allowed to open this page">
        <tr lang="de"> Sie können diese Seite nicht öffnen </tr>
      </string>
      <string key="Resume has been saved">
        <tr lang="de"> Lebenslauf wurde gespeichert </tr>
      </string>
      <string key="Send applications online via web site">
        <tr lang="de"> Bewerbung online über Website senden </tr>
      </string>
      <string key="Job Alert Name">
        <tr lang="de"> Job-Alarm-Name </tr>
      </string>
      <string key="Add new job alert">
        <tr lang="de"> Neuen Job-Alarm hinzufügen </tr>
      </string>
      <string key="Jobs Applied">
        <tr lang="de"> Laufende Bewerbungen </tr>
      </string>
      <string key="Company Search Results">
        <tr lang="de"> Firma Suchergebnisse </tr>
      </string>
      <string key="Mark as Read">
        <tr lang="de"> Als gelesen markieren </tr>
      </string>
      <string key="Message from">
        <tr lang="de"> Nachricht von </tr>
      </string>
      <string key="Read Private Message">
        <tr lang="de"> Persönliche Nachricht lesen </tr>
      </string>
      <string key="Reply">
        <tr lang="de"> Antworten </tr>
      </string>
      <string key="Approve selected">
        <tr lang="de"> Gewählte annehmen </tr>
      </string>
      <string key="Reject selected">
        <tr lang="de"> Gewählte ablehnen </tr>
      </string>
      <string key="Pending">
        <tr lang="de"> In Bearbeitung </tr>
      </string>
      <string key="Approved">
        <tr lang="de"> Angenommen </tr>
      </string>
      <string key="Rejected">
        <tr lang="de"> Abgelehnt </tr>
      </string>
      <string key="Select Job Posting">
        <tr lang="de"> Job-Eintrag auswählen </tr>
      </string>
      <string key="All Jobs">
        <tr lang="de"> Alle Jobs </tr>
      </string>
      <string key="Delete profile">
        <tr lang="de"> Profil löschen </tr>
      </string>
      <string key="Back">
        <tr lang="de"> Zurück </tr>
      </string>
      <string key="Enable">
        <tr lang="de"> Aktivieren </tr>
      </string>
      <string key="Email frequency">
        <tr lang="de"> E-Mail-Häufigkeit </tr>
      </string>
      <string key="Subscription date">
        <tr lang="de"> Datum der Registrierung </tr>
      </string>
      <string key="Subscription expiration date">
        <tr lang="de"> Ende der Mitgliedschaft </tr>
      </string>
      <string key="Not Available Anymore">
        <tr lang="de"> Nicht mehr verfügbar </tr>
      </string>
      <string key="home">
        <tr lang="de"> Home </tr>
      </string>
      <string key="Search job title only">
        <tr lang="de"> Nur Job-Titel durchsuchen </tr>
      </string>
      <string key="Edit notes">
        <tr lang="de"> Notizen bearbeiten </tr>
      </string>
      <string key="Add notes">
        <tr lang="de"> Notiz hinzufügen </tr>
      </string>
      <string key="Close">
        <tr lang="de"> Schließen </tr>
      </string>
      <string key="My notes">
        <tr lang="de"> Meine Notizen </tr>
      </string>
      <string key="Search resume title only">
        <tr lang="de"> Nur CV-Titel durchsuchen </tr>
      </string>
      <string key="Search by title">
        <tr lang="de"> Titel suchen </tr>
      </string>
      <string key="Match exact phrase">
        <tr lang="de"> Genauen Wortlaut suchen </tr>
      </string>
      <string key="Match all words">
        <tr lang="de"> Mit all diesen Begriffen </tr>
      </string>
      <string key="Match any words">
        <tr lang="de"> Mit einem dieser Begriffe </tr>
      </string>
      <string key="Boolean">
        <tr lang="de"> Boolean </tr>
      </string>
      <string key="Boolean search description">
        <tr lang="de"> Such-Beschreibung (Boolean) </tr>
      </string>
      <string key="Terms of use">
        <tr lang="de"> Nutzungsregeln </tr>
      </string>
      <string key="Test URL">
        <tr lang="de"> Test-URL </tr>
      </string>
      <string key="Go Search">
        <tr lang="de"> Suche beginnen </tr>
      </string>
      <string key="Total">
        <tr lang="de"> Insgesamt </tr>
      </string>
      <string key="Employers List">
        <tr lang="de"> Liste der Arbeitgeber </tr>
      </string>
      <string key="Selected Employers">
        <tr lang="de"> Ausgewählte Arbeitgeber </tr>
      </string>
      <string key="* Use CTRL key to select two or more employers">