<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE translation2 [
<!ELEMENT translation2 (languages,pages)>
<!ELEMENT languages (lang*)>
<!ELEMENT lang (#PCDATA)>
<!ATTLIST lang id ID #REQUIRED>
<!ELEMENT pages (page*)>
<!ELEMENT page (string*)>
<!ATTLIST page key CDATA #REQUIRED>
<!ELEMENT string (tr*)>
<!ATTLIST string key CDATA #REQUIRED>
<!ELEMENT tr (#PCDATA)>
<!ATTLIST tr lang IDREF #REQUIRED>
]>

<translation2>
  <languages>
    <lang id="nl"/>
  </languages>
  <pages>
    <page key="Frontend">
      <string key="City is not set">
        <tr lang="nl">  </tr>
      </string>
      <string key="ZIP code is not set">
        <tr lang="nl">  </tr>
      </string>
      <string key="Billing address is not set">
        <tr lang="nl">  </tr>
      </string>
      <string key="CSC value is not set">
        <tr lang="nl">  </tr>
      </string>
      <string key="Credit card number is not set">
        <tr lang="nl">  </tr>
      </string>
      <string key="User last name is not set">
        <tr lang="nl">  </tr>
      </string>
      <string key="Expiration year is not set">
        <tr lang="nl">  </tr>
      </string>
      <string key="Expiration month is not set">
        <tr lang="nl">  </tr>
      </string>
      <string key="User name is not set">
        <tr lang="nl">  </tr>
      </string>
      <string key="Applications">
        <tr lang="nl"> Sollicitaties </tr>
      </string>
      <string key="Job Search">
        <tr lang="nl"> Vacature zoeken </tr>
      </string>
      <string key="Find">
        <tr lang="nl"> Zoek </tr>
      </string>
      <string key="Advanced search">
        <tr lang="nl"> Uitgebreid zoeken </tr>
      </string>
      <string key="Home">
        <tr lang="nl"> Home </tr>
      </string>
      <string key="Register">
        <tr lang="nl"> Registreren </tr>
      </string>
      <string key="Sign In">
        <tr lang="nl"> Inloggen </tr>
      </string>
      <string key="My Account">
        <tr lang="nl"> Mijn account </tr>
      </string>
      <string key="Find Jobs">
        <tr lang="nl"> Zoek vacature </tr>
      </string>
      <string key="Post Resumes">
        <tr lang="nl"> Plaats cv </tr>
      </string>
      <string key="Search Resumes">
        <tr lang="nl"> Zoek cv </tr>
      </string>
      <string key="Post Jobs">
        <tr lang="nl"> Plaats vacature </tr>
      </string>
      <string key="Contact">
        <tr lang="nl"> Contact </tr>
      </string>
      <string key="Choose language">
        <tr lang="nl"> Kies taal </tr>
      </string>
      <string key="Jobs by Category">
        <tr lang="nl"> Vacatures per branche </tr>
      </string>
      <string key="Jobs by City">
        <tr lang="nl"> Vacatures per plaats </tr>
      </string>
      <string key="Featured Jobs">
        <tr lang="nl"> Vacatures uitgelicht </tr>
      </string>
      <string key="Employers">
        <tr lang="nl"> Werkgevers </tr>
      </string>
      <string key="Search resumes">
        <tr lang="nl"> Zoek cv </tr>
      </string>
      <string key="Job Seekers">
        <tr lang="nl"> Werknemers </tr>
      </string>
      <string key="Post resumes">
        <tr lang="nl"> Plaats cv </tr>
      </string>
      <string key="Find jobs">
        <tr lang="nl"> Zoek vacatures </tr>
      </string>
      <string key="RSS Feed">
        <tr lang="nl"> RSS Feed </tr>
      </string>
      <string key="Latest Jobs">
        <tr lang="nl"> Laatste vacatures </tr>
      </string>
      <string key="Keep me signed in">
        <tr lang="nl"> Ik wil ingelogd blijven </tr>
      </string>
      <string key="Login">
        <tr lang="nl"> Login </tr>
      </string>
      <string key="Forgot Your Password?">
        <tr lang="nl"> Wachtwoord vergeten? </tr>
      </string>
      <string key="Registration">
        <tr lang="nl"> Registratie </tr>
      </string>
      <string key="Salutation First and Last Name">
        <tr lang="nl"> Voornaam en achternaam </tr>
      </string>
      <string key="Email">
        <tr lang="nl"> E-mail </tr>
      </string>
      <string key="Comments">
        <tr lang="nl"> Opmerkingen </tr>
      </string>
      <string key="Submit">
        <tr lang="nl"> Verstuur </tr>
      </string>
      <string key="Please select the appropriate user group">
        <tr lang="nl"> Selecteer een gebruikersgroep </tr>
      </string>
      <string key="Confirm Password">
        <tr lang="nl"> Bevestig wachtwoord </tr>
      </string>
      <string key="You have successfully registered in our site">
        <tr lang="nl"> Je bent succesvol ingeschreven op onze website </tr>
      </string>
      <string key="Add a New Listing">
        <tr lang="nl"> Voeg een nieuw contact toe </tr>
      </string>
      <string key="You specified wrong username">
        <tr lang="nl"> Verkeerde gebruikersnaam </tr>
      </string>
      <string key="Invalid payment ID is specified">
        <tr lang="nl"> Ongeldige betalings-ID </tr>
      </string>
      <string key="Search">
        <tr lang="nl"> Zoek </tr>
      </string>
      <string key="My Jobs">
        <tr lang="nl"> Mijn vacatures </tr>
      </string>
      <string key="My Profile">
        <tr lang="nl"> Mijn cv </tr>
      </string>
      <string key="Saved Searches">
        <tr lang="nl"> Bewaarde zoekopdrachten </tr>
      </string>
      <string key="Saved Listings">
        <tr lang="nl"> Bewaarde vacatures </tr>
      </string>
      <string key="My Notifications">
        <tr lang="nl"> Mijn notificaties </tr>
      </string>
      <string key="Billing History">
        <tr lang="nl"> Betaalgeschiedenis </tr>
      </string>
      <string key="Logout">
        <tr lang="nl"> Uitloggen </tr>
      </string>
      <string key="My Listings">
        <tr lang="nl"> Mijn vacatures </tr>
      </string>
      <string key="Filter">
        <tr lang="nl"> Filter </tr>
      </string>
      <string key="unlimited">
        <tr lang="nl"> ongelimiteerd </tr>
      </string>
      <string key="Next">
        <tr lang="nl"> Volgende </tr>
      </string>
      <string key="Edit Listing">
        <tr lang="nl"> Bewerk vacatures </tr>
      </string>
      <string key="Upgrade to Featured">
        <tr lang="nl"> Upgraden naar speciaal </tr>
      </string>
      <string key="You have already subscribed">
        <tr lang="nl"> Je bent al ingeschreven </tr>
      </string>
      <string key="No listings found.">
        <tr lang="nl"> Geen vacatures gevonden. </tr>
      </string>
      <string key="Listing ID is not defined">
        <tr lang="nl"> Vacature ID is niet gedefinieerd </tr>
      </string>
      <string key="Save">
        <tr lang="nl"> Opslaan </tr>
      </string>
      <string key="Image format is not supported">
        <tr lang="nl"> bestandsformaat wordt niet ondersteund </tr>
      </string>
      <string key="You have successfully changed your profile info!">
        <tr lang="nl"> Je hebt succesvol je profiel aangepast! </tr>
      </string>
      <string key="Delete">
        <tr lang="nl"> Verwijder </tr>
      </string>
      <string key="File deleted successfully">
        <tr lang="nl"> Bestand succesvol verwijderd </tr>
      </string>
      <string key="Back to edit profile">
        <tr lang="nl"> Terug naar cv bewerken </tr>
      </string>
      <string key="You have not saved any searches yet.">
        <tr lang="nl"> Je hebt nog geen zoekopdrachten bewaard. </tr>
      </string>
      <string key="ID">
        <tr lang="nl"> ID </tr>
      </string>
      <string key="Period">
        <tr lang="nl"> Periode </tr>
      </string>
      <string key="from">
        <tr lang="nl"> van </tr>
      </string>
      <string key="to">
        <tr lang="nl"> naar </tr>
      </string>
      <string key="Date">
        <tr lang="nl"> Datum </tr>
      </string>
      <string key="Description">
        <tr lang="nl"> Omschrijving </tr>
      </string>
      <string key="Amount">
        <tr lang="nl"> Bedrag </tr>
      </string>
      <string key="Action">
        <tr lang="nl"> Mogelijkheden </tr>
      </string>
      <string key="Total Amount">
        <tr lang="nl"> Totaalbedrag </tr>
      </string>
      <string key="There are no saved listings">
        <tr lang="nl"> Er zijn geen bewaarde vacatures </tr>
      </string>
      <string key="Notify on Listing Activation">
        <tr lang="nl"> Berichten over de activatie van de listing </tr>
      </string>
      <string key="Modify search">
        <tr lang="nl"> Pas zoekopdracht aan </tr>
      </string>
      <string key="Saved jobs">
        <tr lang="nl"> Bewaarde vacatures </tr>
      </string>
      <string key="Saved searches">
        <tr lang="nl"> Bewaarde zoekopdrachten </tr>
      </string>
      <string key="Number of jobs per page">
        <tr lang="nl"> Aantal vacatures per pagina </tr>
      </string>
      <string key="Previous">
        <tr lang="nl"> Vorige </tr>
      </string>
      <string key="Save Your Search">
        <tr lang="nl"> Bewaar je zoekopdracht </tr>
      </string>
      <string key="Search Name">
        <tr lang="nl"> Naam zoekopdracht </tr>
      </string>
      <string key="Your search has been saved.">
        <tr lang="nl"> Je zoekopdracht is bewaard. </tr>
      </string>
      <string key="You may close this window now.">
        <tr lang="nl"> Je mag dit window nu sluiten. </tr>
      </string>
      <string key="Save ad">
        <tr lang="nl"> Bewaar advertentie </tr>
      </string>
      <string key="View job details">
        <tr lang="nl"> Bekijk vacature </tr>
      </string>
      <string key="Please, Vote!">
        <tr lang="nl"> Stem! </tr>
      </string>
      <string key="Watch a video">
        <tr lang="nl"> Bekijk een video </tr>
      </string>
      <string key="Save this Job">
        <tr lang="nl"> Bewaar deze vacature </tr>
      </string>
      <string key="View Saved Jobs">
        <tr lang="nl"> Bekijk bewaarde vacatures </tr>
      </string>
      <string key="Tell a Friend">
        <tr lang="nl"> Vertel verder </tr>
      </string>
      <string key="Print This Ad">
        <tr lang="nl"> Print deze advertentie </tr>
      </string>
      <string key="Map View">
        <tr lang="nl"> Kaart View </tr>
      </string>
      <string key="Back to Results">
        <tr lang="nl"> Terug naar resultaten </tr>
      </string>
      <string key="Modify Search">
        <tr lang="nl"> Zoekopdracht aanpassen </tr>
      </string>
      <string key="Rate This Job">
        <tr lang="nl"> Beoordeel deze vacature </tr>
      </string>
      <string key="User Info">
        <tr lang="nl"> Gebruikers informatie </tr>
      </string>
      <string key="Video">
        <tr lang="nl"> Video </tr>
      </string>
      <string key="Apply Now">
        <tr lang="nl"> Solliciteer </tr>
      </string>
      <string key="Location">
        <tr lang="nl"> Locatie </tr>
      </string>
      <string key="Please wait ...">
        <tr lang="nl"> Even wachten aub ... </tr>
      </string>
      <string key="Add your comment">
        <tr lang="nl"> Opmerking toevoegen </tr>
      </string>
      <string key="Add">
        <tr lang="nl"> Toevoegen </tr>
      </string>
      <string key="View details">
        <tr lang="nl"> Bekijk meer </tr>
      </string>
      <string key="Recommend">
        <tr lang="nl"> Aanbevelen </tr>
      </string>
      <string key="Your name">
        <tr lang="nl"> Uw naam </tr>
      </string>
      <string key="Send">
        <tr lang="nl"> Verstuur </tr>
      </string>
      <string key="Cannot send letter">
        <tr lang="nl"> Kan bericht niet versturen </tr>
      </string>
      <string key="Company Info">
        <tr lang="nl"> Bedrijfs informatie </tr>
      </string>
      <string key="You&apos;ve already voted">
        <tr lang="nl"> Je hebt al gestemd </tr>
      </string>
      <string key="Author">
        <tr lang="nl"> Auteur </tr>
      </string>
      <string key="Your e-mail">
        <tr lang="nl"> Jouw e-mail </tr>
      </string>
      <string key="Attach your resume">
        <tr lang="nl"> Voeg cv toe </tr>
      </string>
      <string key="Number of resumes per page">
        <tr lang="nl"> Aantal cvs per pagina </tr>
      </string>
      <string key="Add Pictures">
        <tr lang="nl"> Voeg afbeelding toe </tr>
      </string>
      <string key="is empty">
        <tr lang="nl"> is leeg </tr>
      </string>
      <string key="is unknown">
        <tr lang="nl"> is niet bekend </tr>
      </string>
      <string key="Manage Listing">
        <tr lang="nl"> Beheer vacature </tr>
      </string>
      <string key="Preview Listing">
        <tr lang="nl"> Bekijk vacature </tr>
      </string>
      <string key="Add Picture">
        <tr lang="nl"> Voeg afbeelding toe </tr>
      </string>
      <string key="Caption">
        <tr lang="nl"> Bijschrift </tr>
      </string>
      <string key="Thumbnail">
        <tr lang="nl"> Thumbnail </tr>
      </string>
      <string key="Actions">
        <tr lang="nl"> Mogelijkheden </tr>
      </string>
      <string key="Are you sure?">
        <tr lang="nl"> Weet je het zeker? </tr>
      </string>
      <string key="Edit Picture">
        <tr lang="nl"> Bewerk afbeelding </tr>
      </string>
      <string key="Picture">
        <tr lang="nl"> Afbeelding </tr>
      </string>
      <string key="Please specify a valid email address.">
        <tr lang="nl"> Voer een geldig e-mailadres in. </tr>
      </string>
      <string key="Please provide your full name.">
        <tr lang="nl"> Voer je volledige naam in. </tr>
      </string>
      <string key="Please include your comments.">
        <tr lang="nl"> Voeg je opmerkingen toe. </tr>
      </string>
      <string key="Thank you very much for your message. We will respond to you as soon as possible.">
        <tr lang="nl"> Dank voor je bericht, we nemen zo spoedig mogelijk contact met u op. </tr>
      </string>
      <string key="Login error">
        <tr lang="nl"> Ongeldige gebruikersnaam en/of wachtwoord </tr>
      </string>
      <string key="Browse by category">
        <tr lang="nl"> Bekijk op categorie </tr>
      </string>
      <string key="Browse by city">
        <tr lang="nl"> Bekijk per stad </tr>
      </string>
      <string key="My Resumes">
        <tr lang="nl"> Mijn cvs </tr>
      </string>
      <string key="Saved Jobs">
        <tr lang="nl"> Opgeslagen vacatures </tr>
      </string>
      <string key="Job Alerts">
        <tr lang="nl"> Vacaturemeldingen </tr>
      </string>
      <string key="$select_box_field_distance of Zip $input_text_field_location">
        <tr lang="nl"> $select_box_field_distance of Zip $input_text_field_location </tr>
      </string>
      <string key="$input_text_field_from to $input_text_field_to">
        <tr lang="nl"> $input_text_field_from to $input_text_field_to </tr>
      </string>
      <string key="not confirmed">
        <tr lang="nl"> niet bevestigd </tr>
      </string>
      <string key="this value is already used in the system">
        <tr lang="nl"> deze waarde is al in gebruik in het systeem </tr>
      </string>
      <string key="Actions with Selected">
        <tr lang="nl"> Mogelijkheden met geselecteerd </tr>
      </string>
      <string key="Number of listings per page">
        <tr lang="nl"> Aantal vacatures per pagina </tr>
      </string>
      <string key="Deactivate">
        <tr lang="nl"> Deactiveer </tr>
      </string>
      <string key="Activate">
        <tr lang="nl"> Activeer </tr>
      </string>
      <string key="Your listing is successfully activated">
        <tr lang="nl"> Je vacature is succesvol geactiveerd </tr>
      </string>
      <string key="Back to My Listings">
        <tr lang="nl"> Terug naar mijn vacatures </tr>
      </string>
      <string key="Sort by">
        <tr lang="nl"> Sorteer op </tr>
      </string>
      <string key="Edit">
        <tr lang="nl"> Bewerk </tr>
      </string>
      <string key="Jobs by $companyName">
        <tr lang="nl"> Vacatures van $companyName </tr>
      </string>
      <string key="View resume details">
        <tr lang="nl"> Bekijk cv details </tr>
      </string>
      <string key="All resumes by this user">
        <tr lang="nl"> Alle cvs van deze gebruiker </tr>
      </string>
      <string key="Rate This Resume">
        <tr lang="nl"> Waardeer dit cv </tr>
      </string>
      <string key="View Saved Resumes">
        <tr lang="nl"> Bekijk opgeslagen cvs </tr>
      </string>
      <string key="Save this Resume">
        <tr lang="nl"> CV opslaan </tr>
      </string>
      <string key="Resumes by $firstName $lastName">
        <tr lang="nl"> CV van $firstName $lastName </tr>
      </string>
      <string key="is not an integer value">
        <tr lang="nl"> is geen integere waarde </tr>
      </string>
      <string key="limit exceeded">
        <tr lang="nl"> limiet overschreden </tr>
      </string>
      <string key="You don&apos;t have permissions to access this page.">
        <tr lang="nl"> Je hebtgeen toegang tot deze pagina. </tr>
      </string>
      <string key="Your friend&apos;s name">
        <tr lang="nl"> Naam vriend(in) </tr>
      </string>
      <string key="Your friend&apos;s e-mail address">
        <tr lang="nl"> E-mail vriend(in) </tr>
      </string>
      <string key="Dear customer!">
        <tr lang="nl"> Beste klant! </tr>
      </string>
      <string key="Please choose from the following payment methods:">
        <tr lang="nl"> Kies betaalmethode: </tr>
      </string>
      <string key="Wire Transfer">
        <tr lang="nl"> Telefonisch overboeken </tr>
      </string>
      <string key="Anonymous User Info">
        <tr lang="nl"> Anonieme gebrukersinformatie </tr>
      </string>
      <string key="Welcome">
        <tr lang="nl"> Welkom </tr>
      </string>
      <string key="Please log in to access this page. If you do not have an account, please">
        <tr lang="nl"> Log in a.u.b. om naar deze pagina te gaan. Als u geen account hebt, </tr>
      </string>
      <string key="Featured Companies">
        <tr lang="nl"> Bedrijven in de spotlight </tr>
      </string>
      <string key="Get Resumes by Email">
        <tr lang="nl"> Ontvang cvs per e-mail </tr>
      </string>
      <string key="Get Jobs by Email">
        <tr lang="nl"> Ontvang vacatures per e-mail </tr>
      </string>
      <string key="Confirm E-mail">
        <tr lang="nl"> Bevestig e-mailadres </tr>
      </string>
      <string key="Reload Image">
        <tr lang="nl"> Herlaad afbeelding </tr>
      </string>
      <string key="Accept terms of use">
        <tr lang="nl"> Accepteer gebruiksvoorwaarden </tr>
      </string>
      <string key="Read terms of use">
        <tr lang="nl"> Lees gebruiksvoorwaarden </tr>
      </string>
      <string key="Resume Alerts">
        <tr lang="nl"> CV alerts </tr>
      </string>
      <string key="Application Tracking">
        <tr lang="nl"> Aanvraag volgen </tr>
      </string>
      <string key="Resume Alert Name">
        <tr lang="nl"> Naam cv alert </tr>
      </string>
      <string key="Add new resume alert">
        <tr lang="nl"> Nieuw cv alert toevoegen </tr>
      </string>
      <string key="Disable">
        <tr lang="nl"> Stoppen </tr>
      </string>
      <string key="Preview Search Results">
        <tr lang="nl"> Voorbeeld zoekresultaten </tr>
      </string>
      <string key="Add resume alert">
        <tr lang="nl"> Add resume alert </tr>
      </string>
      <string key="Alert Name">
        <tr lang="nl"> Alert Name </tr>
      </string>
      <string key="Date Applied">
        <tr lang="nl"> Datum toegepast </tr>
      </string>
      <string key="Status">
        <tr lang="nl"> Status </tr>
      </string>
      <string key="Attached Resume">
        <tr lang="nl"> Aangehecht cv </tr>
      </string>
      <string key="Applicant’s Name">
        <tr lang="nl"> Naam van de aanvrager </tr>
      </string>
      <string key="View Attached File">
        <tr lang="nl"> Bekijk attachment </tr>
      </string>
      <string key="Job Search Results">
        <tr lang="nl"> Vacature zoekresultaten </tr>
      </string>
      <string key="Company Profile">
        <tr lang="nl"> Bedrijfsprofiel </tr>
      </string>
      <string key="here">
        <tr lang="nl"> hier </tr>
      </string>
      <string key="to add a new listing.">
        <tr lang="nl"> Een vacature toevoegen. </tr>
      </string>
      <string key="Fields marked with an asterisk (">
        <tr lang="nl"> Velden met een sterretje ( </tr>
      </string>
      <string key=") are mandatory">
        <tr lang="nl"> ) zijn verplicht </tr>
      </string>
      <string key="Please log in to place a listing. If you do not have an account, please">
        <tr lang="nl"> U dient eerst in te loggen wanneer u een vacature wilt plaatsen. Heeft u nog geen account klik </tr>
      </string>
      <string key="within $radius $radius_search_unit of $location">
        <tr lang="nl"> binnen $radius $radius_search_unit van $location </tr>
      </string>
      <string key="Apply to job">
        <tr lang="nl"> Reageer op vacature </tr>
      </string>
      <string key="Cover letter (optional)">
        <tr lang="nl"> Sollicitatiebrief (optioneel) </tr>
      </string>
      <string key="You applied successfully">
        <tr lang="nl"> Je hebt succesvol gesolliciteerd </tr>
      </string>
      <string key="Please log in to place a new posting. If you do not have an account, please">
        <tr lang="nl"> U dient in te loggen om een nieuwe vacature te plaatsen. Als je geen account hebt, a.u.b. </tr>
      </string>
      <string key="Register.">
        <tr lang="nl"> Registreer. </tr>
      </string>
      <string key="Search by Company">
        <tr lang="nl"> Op bedrijfsnaam zoeken </tr>
      </string>
      <string key="Clone">
        <tr lang="nl"> Kopieer </tr>
      </string>
      <string key="My Job Preview">
        <tr lang="nl"> Voorbeeld van mijn vacature </tr>
      </string>
      <string key="Click to select">
        <tr lang="nl"> Klik om te selecteren </tr>
      </string>
      <string key="Redirect to this URL">
        <tr lang="nl"> Verwijs naar deze URL </tr>
      </string>
      <string key="Use the following format:">
        <tr lang="nl"> Gebruik volgend bestandsformaat: </tr>
      </string>
      <string key="Your changes were successfully saved">
        <tr lang="nl"> Je aanpassingen zijn succesvol opgeslagen </tr>
      </string>
      <string key="Manage Pictures">
        <tr lang="nl"> Beheer afbeeldingen </tr>
      </string>
      <string key="Clone Job">
        <tr lang="nl"> Kopieer vacature </tr>
      </string>
      <string key="Company">
        <tr lang="nl"> Bedrijf </tr>
      </string>
      <string key="My Applications">
        <tr lang="nl"> Mijn sollicitaties </tr>
      </string>
      <string key="Select your resume">
        <tr lang="nl"> Selecteer je cv </tr>
      </string>
      <string key="My Postings">
        <tr lang="nl"> Mijn opmerkingen </tr>
      </string>
      <string key="Private messages">
        <tr lang="nl"> Privéberichten </tr>
      </string>
      <string key="Inbox">
        <tr lang="nl"> Inbox </tr>
      </string>
      <string key="Outbox">
        <tr lang="nl"> Outbox </tr>
      </string>
      <string key="Edit Saved Search">
        <tr lang="nl"> Bewerk opgeslagen zoekopdracht </tr>
      </string>
      <string key="Saved Searches Name">
        <tr lang="nl"> Naam zoekopdracht </tr>
      </string>
      <string key="Notify on Jobs Expiration">
        <tr lang="nl"> Stuur bericht wanneer mijn Jobs verlopen </tr>
      </string>
      <string key="Cover Letter">
        <tr lang="nl"> Sollicitatiebrief </tr>
      </string>
      <string key="Compose Message">
        <tr lang="nl"> Maak bericht </tr>
      </string>
      <string key="From">
        <tr lang="nl"> Van </tr>
      </string>
      <string key="Subject">
        <tr lang="nl"> Onderwerp </tr>
      </string>
      <string key="To">
        <tr lang="nl"> Aan </tr>
      </string>
      <string key="Message to">
        <tr lang="nl"> Bericht aan </tr>
      </string>
      <string key="Message">
        <tr lang="nl"> Bericht </tr>
      </string>
      <string key="Save to outbox">
        <tr lang="nl"> Bewaar in outbox </tr>
      </string>
      <string key="Send private message">
        <tr lang="nl"> Stuur privébericht </tr>
      </string>
      <string key="You&apos;re not allowed to open this page">
        <tr lang="nl"> Je mag deze pagina niet bekijken </tr>
      </string>
      <string key="Resume has been saved">
        <tr lang="nl"> CV is opgeslagen </tr>
      </string>
      <string key="Send applications online via web site">
        <tr lang="nl"> Verstuur sollicitaties online via website </tr>
      </string>
      <string key="Notify on Resumes Expiration">
        <tr lang="nl"> Stuur bericht als mijn cv verloopt </tr>
      </string>
      <string key="Job Alert Name">
        <tr lang="nl"> Naam vacature alert </tr>
      </string>
      <string key="Add new job alert">
        <tr lang="nl"> Add new job alert </tr>
      </string>
      <string key="Jobs Applied">
        <tr lang="nl"> Sollicitaties / vacature reacties </tr>
      </string>
      <string key="Company Search Results">
        <tr lang="nl"> Zoekresultaten bedrijf </tr>
      </string>
      <string key="Mark as Read">
        <tr lang="nl"> Markeer als gelezen </tr>
      </string>
      <string key="Message from">
        <tr lang="nl"> Bericht van </tr>
      </string>
      <string key="Read Private Message">
        <tr lang="nl"> Lees privébericht </tr>
      </string>
      <string key="Reply">
        <tr lang="nl"> Beantwoord </tr>
      </string>
      <string key="Approve selected">
        <tr lang="nl"> Keur selectie goed </tr>
      </string>
      <string key="Reject selected">
        <tr lang="nl"> Wijs selectie af </tr>
      </string>
      <string key="Pending">
        <tr lang="nl"> Wachten op goedkeuring </tr>
      </string>
      <string key="Approved">
        <tr lang="nl"> Goedgekeurd </tr>
      </string>
      <string key="Rejected">
        <tr lang="nl"> Afgewezen </tr>
      </string>
      <string key="Select Job Posting">
        <tr lang="nl"> Selecteer vacature </tr>
      </string>
      <string key="All Jobs">
        <tr lang="nl"> Alle vacatures </tr>
      </string>
      <string key="Delete profile">
        <tr lang="nl"> Verwijder profiel </tr>
      </string>
      <string key="Back">
        <tr lang="nl"> Terug </tr>
      </string>
      <string key="Enable">
        <tr lang="nl"> Aanzetten </tr>
      </string>
      <string key="Email frequency">
        <tr lang="nl"> E-mailfrequentie </tr>
      </string>
      <string key="Subscription date">
        <tr lang="nl"> inschrijvingsdatum </tr>
      </string>
      <string key="Subscription expiration date">
        <tr lang="nl"> Vervaldatum </tr>
      </string>
      <string key="Not Available Anymore">
        <tr lang="nl"> Niet meer beschikbaar </tr>
      </string>
      <string key="home">
        <tr lang="nl"> home </tr>
      </string>
      <string key="Search job title only">
        <tr lang="nl"> Zoek alleen in vacature titel </tr>
      </string>
      <string key="Edit notes">
        <tr lang="nl"> Bewerk notities </tr>
      </string>
      <string key="Add notes">
        <tr lang="nl"> Voeg notities toe </tr>
      </string>
      <string key="Close">
        <tr lang="nl"> Sluiten </tr>
      </string>
      <string key="My notes">
        <tr lang="nl"> Mijn notities </tr>
      </string>
      <string key="Search resume title only">
        <tr lang="nl"> Zoek alleen in cv titel </tr>
      </string>
      <string key="Search by title">
        <tr lang="nl"> Zoek op titel </tr>
      </string>
      <string key="Enter code from image">
        <tr lang="nl"> Beveiligingscode </tr>
      </string>
      <string key="Job Seeker">
        <tr lang="nl"> Kandidaat </tr>
      </string>
      <string key="Match exact phrase">
        <tr lang="nl"> Zoek op de exacte zin </tr>
      </string>
      <string key="Match all words">
        <tr lang="nl"> Zoek op alle woorden </tr>
      </string>
      <string key="Match any words">
        <tr lang="nl"> Zoek op ieder woord </tr>
      </string>
      <string key="Boolean">
        <tr lang="nl"> Boolean </tr>
      </string>
      <string key="Boolean search description">
        <tr lang="nl"> Boolean zoekomschrijving </tr>
      </string>
      <string key="Terms of use">
        <tr lang="nl"> Gebruiksvoorwaarden </tr>
      </string>
      <string key="Go Search">
        <tr lang="nl"> Zoek </tr>
      </string>
      <string key="Total">
        <tr lang="nl"> Totaal </tr>
      </string>
      <string key="Selected Employers">
        <tr lang="nl"> Uitgekozen werkgevers </tr>
      </string>
      <string key="* Use CTRL key to select two or more employers">
        <tr lang="nl"> * Gebruik CTRL toest om meerdere bedrijven te selecteren </tr>
      </string>
      <string key="Employers List">
        <tr lang="nl"> Bedrijvenlijst </tr>
      </string>
      <string key="Currency">
        <tr lang="nl"> Munteenheid </tr>
      </string>
      <string key="Deselect all">
        <tr lang="nl"> Deselecteer alles </tr>
      </string>
      <string key="Please choose Excel or csv file">
        <tr lang="nl"> Kies a.u.b. een Excel- of csv-bestand </tr>
      </string>
      <string key="Please, enter your email in the field below and we&apos;ll send you a link to a page where you can change your password">
        <tr lang="nl"> Voer a.u.b uw e-mailadres in in het onderstaande veld en we sturen u een link naar een pagina waar u uw wachtwoord kunt veranderen </tr>
      </string>