<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE translation2 [
<!ELEMENT translation2 (languages,pages)>
<!ELEMENT languages (lang*)>
<!ELEMENT lang (#PCDATA)>
<!ATTLIST lang id ID #REQUIRED>
<!ELEMENT pages (page*)>
<!ELEMENT page (string*)>
<!ATTLIST page key CDATA #REQUIRED>
<!ELEMENT string (tr*)>
<!ATTLIST string key CDATA #REQUIRED>
<!ELEMENT tr (#PCDATA)>
<!ATTLIST tr lang IDREF #REQUIRED>
]>

<translation2>
  <languages>
    <lang id="pt"/>
  </languages>
  <pages>
    <page key="Frontend">
      <string key="City is not set">
        <tr lang="pt">  </tr>
      </string>
      <string key="ZIP code is not set">
        <tr lang="pt">  </tr>
      </string>
      <string key="Billing address is not set">
        <tr lang="pt">  </tr>
      </string>
      <string key="CSC value is not set">
        <tr lang="pt">  </tr>
      </string>
      <string key="Credit card number is not set">
        <tr lang="pt">  </tr>
      </string>
      <string key="User last name is not set">
        <tr lang="pt">  </tr>
      </string>
      <string key="Expiration year is not set">
        <tr lang="pt">  </tr>
      </string>
      <string key="Expiration month is not set">
        <tr lang="pt">  </tr>
      </string>
      <string key="User name is not set">
        <tr lang="pt">  </tr>
      </string>
      <string key="Applications">
        <tr lang="pt"> Aplicações </tr>
      </string>
      <string key="Job Search">
        <tr lang="pt"> Pesquisar Vagas </tr>
      </string>
      <string key="Find">
        <tr lang="pt"> Pesquisar </tr>
      </string>
      <string key="Advanced search">
        <tr lang="pt"> Busca Avançada </tr>
      </string>
      <string key="Home">
        <tr lang="pt"> Página Inicial </tr>
      </string>
      <string key="Register">
        <tr lang="pt"> Cadastre </tr>
      </string>
      <string key="Sign In">
        <tr lang="pt"> Login </tr>
      </string>
      <string key="My Account">
        <tr lang="pt"> Minha Pasta </tr>
      </string>
      <string key="Find Jobs">
        <tr lang="pt"> Pesquisar Vagas </tr>
      </string>
      <string key="Post Resumes">
        <tr lang="pt"> Cadastrar Currículo </tr>
      </string>
      <string key="Search Resumes">
        <tr lang="pt"> Pesquisar Currículos </tr>
      </string>
      <string key="Post Jobs">
        <tr lang="pt"> Cadastrar Vagas </tr>
      </string>
      <string key="Contact">
        <tr lang="pt"> Contato </tr>
      </string>
      <string key="Choose language">
        <tr lang="pt"> Escolher Idioma </tr>
      </string>
      <string key="Jobs by Category">
        <tr lang="pt"> Vagas por Área Profissional </tr>
      </string>
      <string key="Jobs by City">
        <tr lang="pt"> Vagas por Cidade </tr>
      </string>
      <string key="Featured Jobs">
        <tr lang="pt"> Vagas Destacadas </tr>
      </string>
      <string key="Employers">
        <tr lang="pt"> Empresas </tr>
      </string>
      <string key="Search resumes">
        <tr lang="pt"> Busca de Currículos </tr>
      </string>
      <string key="Job Seekers">
        <tr lang="pt"> Candidatos </tr>
      </string>
      <string key="Post resumes">
        <tr lang="pt"> Anuncie seu Currículo </tr>
      </string>
      <string key="Find jobs">
        <tr lang="pt"> Buscar Vagas </tr>
      </string>
      <string key="RSS Feed">
        <tr lang="pt"> RSS Feed </tr>
      </string>
      <string key="Latest Jobs">
        <tr lang="pt"> Vagas Recentes </tr>
      </string>
      <string key="Keep me signed in">
        <tr lang="pt"> Mantenha-me Conectado </tr>
      </string>
      <string key="Login">
        <tr lang="pt"> Login </tr>
      </string>
      <string key="Forgot Your Password?">
        <tr lang="pt"> Esqueceu sua Senha? </tr>
      </string>
      <string key="Registration">
        <tr lang="pt"> Cadastro </tr>
      </string>
      <string key="Salutation First and Last Name">
        <tr lang="pt"> Nome e Sobrenome </tr>
      </string>
      <string key="Email">
        <tr lang="pt"> Email </tr>
      </string>
      <string key="Comments">
        <tr lang="pt"> Comentários </tr>
      </string>
      <string key="Submit">
        <tr lang="pt"> Enviar </tr>
      </string>
      <string key="Please select the appropriate user group">
        <tr lang="pt"> Candidato ou Empresa? </tr>
      </string>
      <string key="Confirm Password">
        <tr lang="pt"> Confirmar Senha </tr>
      </string>
      <string key="You have successfully registered in our site">
        <tr lang="pt"> Registro cadastrado com sucesso </tr>
      </string>
      <string key="Add a New Listing">
        <tr lang="pt"> Adicionar </tr>
      </string>
      <string key="You specified wrong username">
        <tr lang="pt"> Usuário Incorreto </tr>
      </string>
      <string key="Invalid payment ID is specified">
        <tr lang="pt"> Identificação de Pagamento Inválido </tr>
      </string>
      <string key="Search">
        <tr lang="pt"> Buscar </tr>
      </string>
      <string key="My Jobs">
        <tr lang="pt"> Minhas Vagas </tr>
      </string>
      <string key="My Profile">
        <tr lang="pt"> Meu Perfil </tr>
      </string>
      <string key="Saved Searches">
        <tr lang="pt"> Buscas Armazenadas </tr>
      </string>
      <string key="Saved Listings">
        <tr lang="pt"> Vagas Armazenadas </tr>
      </string>
      <string key="My Notifications">
        <tr lang="pt"> Minhas Anotações </tr>
      </string>
      <string key="Billing History">
        <tr lang="pt"> Histórico de Pagamentos </tr>
      </string>
      <string key="Logout">
        <tr lang="pt"> Sair </tr>
      </string>
      <string key="My Listings">
        <tr lang="pt"> Minhas Vagas </tr>
      </string>
      <string key="Filter">
        <tr lang="pt"> Filtro </tr>
      </string>
      <string key="unlimited">
        <tr lang="pt"> Ilimitado </tr>
      </string>
      <string key="Next">
        <tr lang="pt"> Próximo </tr>
      </string>
      <string key="Edit Listing">
        <tr lang="pt"> Editar Vagas </tr>
      </string>
      <string key="Upgrade to Featured">
        <tr lang="pt"> Upgrade para Destacado </tr>
      </string>
      <string key="You have already subscribed">
        <tr lang="pt"> Voce Já é Nosso Assinante </tr>
      </string>
      <string key="No listings found.">
        <tr lang="pt"> Vaga não Encontrada </tr>
      </string>
      <string key="Listing ID is not defined">
        <tr lang="pt"> Código de vaga não Definido </tr>
      </string>
      <string key="Save">
        <tr lang="pt"> Salvar </tr>
      </string>
      <string key="Image format is not supported">
        <tr lang="pt"> Formato de Imagem Recusado </tr>
      </string>
      <string key="You have successfully changed your profile info!">
        <tr lang="pt"> Mudança de Perfil Aceita </tr>
      </string>
      <string key="Delete">
        <tr lang="pt"> Apagar </tr>
      </string>
      <string key="File deleted successfully">
        <tr lang="pt"> Arquivo Apagado Com Sucesso </tr>
      </string>
      <string key="Back to edit profile">
        <tr lang="pt"> Voltar ao Meu Perfil </tr>
      </string>
      <string key="You have not saved any searches yet.">
        <tr lang="pt"> Voce Não Salvou as Mudanças </tr>
      </string>
      <string key="ID">
        <tr lang="pt"> Identificação </tr>
      </string>
      <string key="Period">
        <tr lang="pt"> Período </tr>
      </string>
      <string key="State">
        <tr lang="pt"> Estado </tr>
      </string>
      <string key="from">
        <tr lang="pt"> De </tr>
      </string>
      <string key="to">
        <tr lang="pt"> Até </tr>
      </string>
      <string key="Date">
        <tr lang="pt"> Data </tr>
      </string>
      <string key="Description">
        <tr lang="pt"> Descrição </tr>
      </string>
      <string key="Amount">
        <tr lang="pt"> Valor </tr>
      </string>
      <string key="Action">
        <tr lang="pt"> Ação </tr>
      </string>
      <string key="Total Amount">
        <tr lang="pt"> Valor Total </tr>
      </string>
      <string key="There are no saved listings">
        <tr lang="pt"> Não Existe Vagas Armazenadas </tr>
      </string>
      <string key="Notify on Listing Activation">
        <tr lang="pt"> Informar sobre Vagas Ativas </tr>
      </string>
      <string key="Modify search">
        <tr lang="pt"> Mudar Busca </tr>
      </string>
      <string key="Saved jobs">
        <tr lang="pt"> Vagas Salvas </tr>
      </string>
      <string key="Saved searches">
        <tr lang="pt"> Buscas Armazenadas </tr>
      </string>
      <string key="Number of jobs per page">
        <tr lang="pt"> Número de Vagas por Página </tr>
      </string>
      <string key="Previous">
        <tr lang="pt"> Anterior </tr>
      </string>
      <string key="Save Your Search">
        <tr lang="pt"> Armazenar Buscas </tr>
      </string>
      <string key="Search Name">
        <tr lang="pt"> Buscar Nome </tr>
      </string>
      <string key="Your search has been saved.">
        <tr lang="pt"> A Sua Busca foi Armazenada </tr>
      </string>
      <string key="You may close this window now.">
        <tr lang="pt"> Fechar esta Janela Agora </tr>
      </string>
      <string key="Save ad">
        <tr lang="pt"> Anúncio Salvo </tr>
      </string>
      <string key="View job details">
        <tr lang="pt"> Ver Detalhes da Vaga </tr>
      </string>
      <string key="Please, Vote!">
        <tr lang="pt"> Por favor, Vote! </tr>
      </string>
      <string key="Watch a video">
        <tr lang="pt"> Assistir Video </tr>
      </string>
      <string key="Save this Job">
        <tr lang="pt"> Armazenar Esta Vaga </tr>
      </string>
      <string key="View Saved Jobs">
        <tr lang="pt"> Ver Vagas Armazenadas </tr>
      </string>
      <string key="Tell a Friend">
        <tr lang="pt"> Enviar para um Amigo </tr>
      </string>
      <string key="Print This Ad">
        <tr lang="pt"> Imprimir esta Vaga </tr>
      </string>
      <string key="Map View">
        <tr lang="pt"> Vista de Mapa </tr>
      </string>
      <string key="Back to Results">
        <tr lang="pt"> Voltar aos Resultados de Busca </tr>
      </string>
      <string key="Modify Search">
        <tr lang="pt"> Modificar Busca </tr>
      </string>
      <string key="Rate This Job">
        <tr lang="pt"> Avalie esta Vaga </tr>
      </string>
      <string key="User Info">
        <tr lang="pt"> Informações do Usuário </tr>
      </string>
      <string key="Video">
        <tr lang="pt"> Vídeo </tr>
      </string>
      <string key="Apply Now">
        <tr lang="pt"> Cadastre Agora </tr>
      </string>
      <string key="Location">
        <tr lang="pt"> Localização </tr>
      </string>
      <string key="Please wait ...">
        <tr lang="pt"> Espere, Por Favor </tr>
      </string>
      <string key="Add your comment">
        <tr lang="pt"> Adicionar Comentário </tr>
      </string>
      <string key="Add">
        <tr lang="pt"> Adicionar </tr>
      </string>
      <string key="View details">
        <tr lang="pt"> Ver Detalhes </tr>
      </string>
      <string key="Recommend">
        <tr lang="pt"> Recomendado </tr>
      </string>
      <string key="Your name">
        <tr lang="pt"> Seu Nome </tr>
      </string>
      <string key="Send">
        <tr lang="pt"> Enviar </tr>
      </string>
      <string key="Cannot send letter">
        <tr lang="pt"> Carta Não Pode Ser Enviada </tr>
      </string>
      <string key="Company Info">
        <tr lang="pt"> Informações da Empresa </tr>
      </string>
      <string key="You&apos;ve already voted">
        <tr lang="pt"> Já votou </tr>
      </string>
      <string key="Author">
        <tr lang="pt"> Autor </tr>
      </string>
      <string key="Your e-mail">
        <tr lang="pt"> Seu Email </tr>
      </string>
      <string key="Attach your resume">
        <tr lang="pt"> Anexar Currículo </tr>
      </string>
      <string key="Number of resumes per page">
        <tr lang="pt"> Número de Currículos por Página </tr>
      </string>
      <string key="Add Pictures">
        <tr lang="pt"> Adicionar Fotos </tr>
      </string>
      <string key="is empty">
        <tr lang="pt"> Está Vazio </tr>
      </string>
      <string key="is unknown">
        <tr lang="pt"> Desconhecido </tr>
      </string>
      <string key="Manage Listing">
        <tr lang="pt"> Gerenciar </tr>
      </string>
      <string key="Preview Listing">
        <tr lang="pt"> Mensagens Anteriores </tr>
      </string>
      <string key="Add Picture">
        <tr lang="pt"> Adicionar Foto </tr>
      </string>
      <string key="Caption">
        <tr lang="pt"> Nome </tr>
      </string>
      <string key="Thumbnail">
        <tr lang="pt"> Miniatura </tr>
      </string>
      <string key="Actions">
        <tr lang="pt"> Ações </tr>
      </string>
      <string key="Are you sure?">
        <tr lang="pt"> Tem Certeza? </tr>
      </string>
      <string key="Edit Picture">
        <tr lang="pt"> Editar Foto </tr>
      </string>
      <string key="Picture">
        <tr lang="pt"> Imagem </tr>
      </string>
      <string key="Please specify a valid email address.">
        <tr lang="pt"> Email Válido </tr>
      </string>
      <string key="Please provide your full name.">
        <tr lang="pt"> Nome Completo </tr>
      </string>
      <string key="Please include your comments.">
        <tr lang="pt"> Faça Seus Comentários </tr>
      </string>
      <string key="Thank you very much for your message. We will respond to you as soon as possible.">
        <tr lang="pt"> Obrigado pela sua mensagem. Responderemos-a o mais rápido possível </tr>
      </string>
      <string key="Login error">
        <tr lang="pt"> Login ou Senha Invalidos </tr>
      </string>
      <string key="Browse by category">
        <tr lang="pt"> Busca por Categoria </tr>
      </string>
      <string key="There are no listings with requested parameters in the system.">
        <tr lang="pt"> Não Existe as Vagas Procuradas </tr>
      </string>
      <string key="Browse by city">
        <tr lang="pt"> Busca por Cidade </tr>
      </string>
      <string key="My Resumes">
        <tr lang="pt"> Meus Curríulos </tr>
      </string>
      <string key="Saved Jobs">
        <tr lang="pt"> Vagas Armazenadas </tr>
      </string>
      <string key="Job Alerts">
        <tr lang="pt"> Aviso de Vagas </tr>
      </string>
      <string key="$select_box_field_distance of Zip $input_text_field_location">
        <tr lang="pt"> $select_box_field_distancia de codigo de area $input_text_field_location </tr>
      </string>
      <string key="$input_text_field_from to $input_text_field_to">
        <tr lang="pt"> $input_text_field_from to $input_text_field_to </tr>
      </string>
      <string key="not confirmed">
        <tr lang="pt"> Não Confirmado </tr>
      </string>
      <string key="this value is already used in the system">
        <tr lang="pt"> Já Está Sendo Usado </tr>
      </string>
      <string key="Actions with Selected">
        <tr lang="pt"> Selecionados </tr>
      </string>
      <string key="Number of listings per page">
        <tr lang="pt"> Número de Vagas por Página </tr>
      </string>
      <string key="Deactivate">
        <tr lang="pt"> Desativar </tr>
      </string>
      <string key="Activate">
        <tr lang="pt"> Ativar </tr>
      </string>
      <string key="Your listing is successfully activated">
        <tr lang="pt"> Ativado com Sucesso </tr>
      </string>
      <string key="Back to My Listings">
        <tr lang="pt"> Voltar as Minhas Vagas </tr>
      </string>
      <string key="Sort by">
        <tr lang="pt"> Selecionar Por </tr>
      </string>
      <string key="Edit">
        <tr lang="pt"> Editar </tr>
      </string>
      <string key="Jobs by $companyName">
        <tr lang="pt"> Vagas $companyName </tr>
      </string>
      <string key="View resume details">
        <tr lang="pt"> Vesualizar Detalhes do Curriculo </tr>
      </string>
      <string key="All resumes by this user">
        <tr lang="pt"> Todos os Currículos deste Usuário </tr>
      </string>
      <string key="Rate This Resume">
        <tr lang="pt"> Avalie Este Curriculo </tr>
      </string>
      <string key="View Saved Resumes">
        <tr lang="pt"> Visualizar Curriculos Armazenados </tr>
      </string>
      <string key="Save this Resume">
        <tr lang="pt"> Salvar Este Curriculo </tr>
      </string>
      <string key="Resumes by $firstName $lastName">
        <tr lang="pt"> CV por $firstName $lastName </tr>
      </string>
      <string key="is not an integer value">
        <tr lang="pt"> Valor Incorreto </tr>
      </string>
      <string key="limit exceeded">
        <tr lang="pt"> O seu Limite Excedeu </tr>
      </string>
      <string key="You don&apos;t have permissions to access this page.">
        <tr lang="pt"> Voce Não tem Permissão para Acessar esta Página </tr>
      </string>
      <string key="Your friend&apos;s name">
        <tr lang="pt"> Nome de seu amigo </tr>
      </string>
      <string key="Your friend&apos;s e-mail address">
        <tr lang="pt"> Email do seu amigo </tr>
      </string>
      <string key="Dear customer!">
        <tr lang="pt"> Prezado Cliente </tr>
      </string>
      <string key="Please choose from the following payment methods:">
        <tr lang="pt"> Por favor, selecione um dos metodos de pagamento: </tr>
      </string>
      <string key="Wire Transfer">
        <tr lang="pt"> Transferência Bancária </tr>
      </string>
      <string key="Anonymous User Info">
        <tr lang="pt"> Informações de Usuário Visitante </tr>
      </string>
      <string key="Welcome">
        <tr lang="pt"> Bemvindo </tr>
      </string>
      <string key="Please log in to access this page. If you do not have an account, please">
        <tr lang="pt"> Por favor, Login para acessar esta página. </tr>
      </string>
      <string key="Featured Companies">
        <tr lang="pt"> Empresas Destacadas </tr>
      </string>
      <string key="Get Resumes by Email">
        <tr lang="pt"> Receber Currículos por Email </tr>
      </string>
      <string key="Get Jobs by Email">
        <tr lang="pt"> Receber Vagas por Email </tr>
      </string>
      <string key="Confirm E-mail">
        <tr lang="pt"> Confirmar E-mail </tr>
      </string>
      <string key="Reload Image">
        <tr lang="pt"> Recaregar Imagem </tr>
      </string>
      <string key="Accept terms of use">
        <tr lang="pt"> Aceitar Condições de Uso </tr>
      </string>
      <string key="Read terms of use">
        <tr lang="pt"> Ler Condições de Uso </tr>
      </string>
      <string key="Resume Alerts">
        <tr lang="pt"> Alertas de Currículos </tr>
      </string>
      <string key="Application Tracking">
        <tr lang="pt"> Andamentos de Processo </tr>
      </string>
      <string key="Resume Alert Name">
        <tr lang="pt"> Nome de Alerta de Currículos </tr>
      </string>
      <string key="Add new resume alert">
        <tr lang="pt"> Adicionar Novo Alerta de Currículo </tr>
      </string>
      <string key="Disable">
        <tr lang="pt"> Desativar </tr>
      </string>
      <string key="Preview Search Results">
        <tr lang="pt"> Visualizar Resultados de Busca </tr>
      </string>
      <string key="Add resume alert">
        <tr lang="pt"> Adicionar Alerta de Currículo </tr>
      </string>
      <string key="Alert Name">
        <tr lang="pt"> Nome de Alerta </tr>
      </string>
      <string key="Job Title">
        <tr lang="pt"> Título da Vaga </tr>
      </string>
      <string key="Date Applied">
        <tr lang="pt"> Data </tr>
      </string>
      <string key="Status">
        <tr lang="pt"> Status </tr>
      </string>
      <string key="Attached Resume">
        <tr lang="pt"> Currículo Anexado </tr>
      </string>
      <string key="Applicant’s Name">
        <tr lang="pt"> Nome do Candidato </tr>
      </string>
      <string key="View Attached File">
        <tr lang="pt"> Visualizar Arquivo Anexado </tr>
      </string>
      <string key="Job Search Results">
        <tr lang="pt"> Resultado da Busca de Vagas </tr>
      </string>
      <string key="Company Profile">
        <tr lang="pt"> Sobre a Empresa </tr>
      </string>
      <string key="here">
        <tr lang="pt"> Aqui </tr>
      </string>
      <string key="to add a new listing.">
        <tr lang="pt"> Para publicar Uma Nova Oferta </tr>
      </string>
      <string key="Fields marked with an asterisk (">
        <tr lang="pt"> Campos Marcados com Asteríistico ( </tr>
      </string>
      <string key=") are mandatory">
        <tr lang="pt"> ) São Obrigatórios </tr>
      </string>
      <string key="Please log in to place a listing. If you do not have an account, please">
        <tr lang="pt"> Conectar para adicionar curriculo. Caso nao seja cadastrado, por favor </tr>
      </string>
      <string key="within $radius $radius_search_unit of $location">
        <tr lang="pt"> entre $radius $radius_search_unit of $location </tr>
      </string>
      <string key="Apply to job">
        <tr lang="pt"> Candidatar-se a Vaga </tr>
      </string>
      <string key="Cover letter (optional)">
        <tr lang="pt"> Carta de Apresentação ( Opcional ) </tr>
      </string>
      <string key="You applied successfully">
        <tr lang="pt"> Voce Candidatou-se a esta Vaga com Sucesso </tr>
      </string>
      <string key="Please log in to place a new posting. If you do not have an account, please">
        <tr lang="pt"> Faça seu login para ter acesso a esta página. Se ainda não é associado, favor </tr>
      </string>
      <string key="Register.">
        <tr lang="pt"> Cadastrar </tr>
      </string>
      <string key="Search by Company">
        <tr lang="pt"> Busca por Empresa </tr>
      </string>
      <string key="Clone">
        <tr lang="pt"> Clone </tr>
      </string>
      <string key="My Job Preview">
        <tr lang="pt"> Visualizar vagas </tr>
      </string>
      <string key="Click to select">
        <tr lang="pt"> Digite para selecionar </tr>
      </string>
      <string key="Redirect to this URL">
        <tr lang="pt"> Encaminhe para este domínio ( URL ) </tr>
      </string>
      <string key="Use the following format:">
        <tr lang="pt"> Use o seguinte formato: </tr>
      </string>
      <string key="Your changes were successfully saved">
        <tr lang="pt"> Suas mudanças foram salvas com sucesso </tr>
      </string>
      <string key="Manage Pictures">
        <tr lang="pt"> Gerenciar imagens </tr>
      </string>
      <string key="Clone Job">
        <tr lang="pt"> Clone a Vaga </tr>
      </string>
      <string key="Company">
        <tr lang="pt"> Empresa </tr>
      </string>
      <string key="My Applications">
        <tr lang="pt"> Meus currículos </tr>
      </string>
      <string key="Select your resume">
        <tr lang="pt"> Selecionar o seu Currícculo </tr>
      </string>
      <string key="My Postings">
        <tr lang="pt"> Meus Anúncios </tr>
      </string>
      <string key="Private messages">
        <tr lang="pt"> Mensagens Privadas </tr>
      </string>
      <string key="Inbox">
        <tr lang="pt"> Caixa de Entrada </tr>
      </string>
      <string key="Outbox">
        <tr lang="pt"> Caixa de Saida </tr>
      </string>
      <string key="Edit Saved Search">
        <tr lang="pt"> Editar Busca Armazenada </tr>
      </string>
      <string key="Saved Searches Name">
        <tr lang="pt"> Armazenar Nomes Procurados </tr>
      </string>
      <string key="Cover Letter">
        <tr lang="pt"> Carta de Apresentação </tr>
      </string>
      <string key="Compose Message">
        <tr lang="pt"> Escrever Mensagem </tr>
      </string>
      <string key="From">
        <tr lang="pt"> De </tr>
      </string>
      <string key="Subject">
        <tr lang="pt"> Assunto </tr>
      </string>
      <string key="To">
        <tr lang="pt"> Para </tr>
      </string>
      <string key="Message to">
        <tr lang="pt"> Mensagem Para </tr>
      </string>
      <string key="Message">
        <tr lang="pt"> Mensagem </tr>
      </string>
      <string key="Save to outbox">
        <tr lang="pt"> Armazenar na Caixa de Saida </tr>
      </string>
      <string key="Send private message">
        <tr lang="pt"> Enviar Mensagem Privada </tr>
      </string>
      <string key="You&apos;re not allowed to open this page">
        <tr lang="pt"> Voce não tem Acesso a Esta Página </tr>
      </string>
      <string key="Resume has been saved">
        <tr lang="pt"> Currículo Armazenado </tr>
      </string>
      <string key="Send applications online via web site">
        <tr lang="pt"> Enviar Currículos Via WebSite </tr>
      </string>
      <string key="Job Alert Name">
        <tr lang="pt"> Nome de Alerta de Vaga </tr>
      </string>
      <string key="Add new job alert">
        <tr lang="pt"> Adicionar novo Alerta de Vaga </tr>
      </string>
      <string key="Jobs Applied">
        <tr lang="pt"> Vagas Que Me Candidatei </tr>
      </string>
      <string key="Company Search Results">
        <tr lang="pt"> Resultados de Busca - Empresas </tr>
      </string>
      <string key="Mark as Read">
        <tr lang="pt"> Marcar como Lida </tr>
      </string>
      <string key="Message from">
        <tr lang="pt"> Mensagem de </tr>
      </string>
      <string key="Read Private Message">
        <tr lang="pt"> Ler Mensagem Privada </tr>
      </string>
      <string key="Reply">
        <tr lang="pt"> Responder </tr>
      </string>
      <string key="Approve selected">
        <tr lang="pt"> Aprovar Selecionado </tr>
      </string>
      <string key="Reject selected">
        <tr lang="pt"> Rejeitar Selecionado </tr>
      </string>
      <string key="Pending">
        <tr lang="pt"> Pendente </tr>
      </string>
      <string key="Approved">
        <tr lang="pt"> Aprovado </tr>
      </string>
      <string key="Rejected">
        <tr lang="pt"> Rejeitado </tr>
      </string>
      <string key="Select Job Posting">
        <tr lang="pt"> Selecionar Vaga Anunciada </tr>
      </string>
      <string key="All Jobs">
        <tr lang="pt"> Todas Vagas </tr>
      </string>
      <string key="Delete profile">
        <tr lang="pt"> Cancelar Perfil </tr>
      </string>
      <string key="Back">
        <tr lang="pt"> Voltar </tr>
      </string>
      <string key="Enable">
        <tr lang="pt"> Autorizar </tr>
      </string>
      <string key="Email frequency">
        <tr lang="pt"> Frequência de E-mails </tr>
      </string>
      <string key="Subscription date">
        <tr lang="pt"> Data do Cadastro </tr>
      </string>
      <string key="Subscription expiration date">
        <tr lang="pt"> Vencimento do Cadastro </tr>
      </string>
      <string key="Not Available Anymore">
        <tr lang="pt"> No Momento não Está Disponiível </tr>
      </string>
      <string key="Match exact phrase">
        <tr lang="pt"> Match a palavra exata </tr>
      </string>
      <string key="Match all words">
        <tr lang="pt"> Match todas palavras </tr>
      </string>
      <string key="Match any words">
        <tr lang="pt"> Match qualquer palavra </tr>
      </string>
      <string key="Boolean">
        <tr lang="pt"> Boolean </tr>
      </string>
      <string key="Search resume title only">
        <tr lang="pt"> Buscar currículos somente por título </tr>
      </string>
      <string key="Edit notes">
        <tr lang="pt"> Corrigir anotações </tr>
      </string>
      <string key="Add notes">
        <tr lang="pt"> Adicionar anotações </tr>
      </string>
      <string key="My notes">
        <tr lang="pt"> Minhas anotações </tr>
      </string>
      <string key="Close">
        <tr lang="pt"> Fechar </tr>
      </string>
      <string key="Boolean search description">
        <tr lang="pt"> BOOLEAN descrição de busca </tr>
      </string>
      <string key="Search job title only">
        <tr lang="pt"> Busca por título de vaga </tr>
      </string>
      <string key="Terms of use">
        <tr lang="pt"> Termos de uso </tr>
      </string>
      <string key="Test URL">
        <tr lang="pt"> Testar URL </tr>
      </string>
      <string key="Go Search">
        <tr lang="pt"> Buscar </tr>
      </string>
      <string key="Total">
        <tr lang="pt"> Total </tr>
      </string>
      <string key="Selected Employers">
        <tr lang="pt"> Empregadores Selecionados </tr>
      </string>
      <string key="* Use CTRL key to select two or more employers">
        <tr lang="pt"> Use a tecla CTRL para selecionar dois ou mais empregadores </tr>
      </string>
      <string key="Employers List">
        <tr lang="pt"> Lista de Empresas </tr>
      </string>
      <string key="Currency">
        <tr lang="pt"> Moeda </tr>
      </string>
      <string key="Deselect all">
        <tr lang="pt"> Descelecionar todos </tr>
      </string>
      <string key="Please choose Excel or csv file">
        <tr lang="pt"> Escolha entre ficheiro Excel ou csv: </tr>
      </string>
      <string key="Please, enter your email in the field below and we&apos;ll send you a link to a page where you can change your password">
        <tr lang="pt"> Insira o seu e-mail no campo abaixo e enviar-lhe-emos um link para aceder a uma página onde pode alterar a sua palavra-passe </tr>
      </string>
      <string key="Your recurring subscription to the &quot;$cancelMembershipPlanName&quot; plan has been canceled.">
        <tr lang="pt">  </tr>
      </string>