<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE translation2 [
<!ELEMENT translation2 (languages,pages)>
<!ELEMENT languages (lang*)>
<!ELEMENT lang (#PCDATA)>
<!ATTLIST lang id ID #REQUIRED>
<!ELEMENT pages (page*)>
<!ELEMENT page (string*)>
<!ATTLIST page key CDATA #REQUIRED>
<!ELEMENT string (tr*)>
<!ATTLIST string key CDATA #REQUIRED>
<!ELEMENT tr (#PCDATA)>
<!ATTLIST tr lang IDREF #REQUIRED>
]>

<translation2>
  <languages>
    <lang id="sr"/>
  </languages>
  <pages>
    <page key="Frontend">
      <string key="City is not set">
        <tr lang="sr">  </tr>
      </string>
      <string key="ZIP code is not set">
        <tr lang="sr">  </tr>
      </string>
      <string key="Billing address is not set">
        <tr lang="sr">  </tr>
      </string>
      <string key="CSC value is not set">
        <tr lang="sr">  </tr>
      </string>
      <string key="Credit card number is not set">
        <tr lang="sr">  </tr>
      </string>
      <string key="User last name is not set">
        <tr lang="sr">  </tr>
      </string>
      <string key="Expiration year is not set">
        <tr lang="sr">  </tr>
      </string>
      <string key="Expiration month is not set">
        <tr lang="sr">  </tr>
      </string>
      <string key="User name is not set">
        <tr lang="sr">  </tr>
      </string>
      <string key="Applications">
        <tr lang="sr"> Апликације </tr>
      </string>
      <string key="Job Search">
        <tr lang="sr"> Претрага Посла </tr>
      </string>
      <string key="Find">
        <tr lang="sr"> Претрага </tr>
      </string>
      <string key="Advanced search">
        <tr lang="sr"> Напредна Претрага </tr>
      </string>
      <string key="Home">
        <tr lang="sr"> Почетна </tr>
      </string>
      <string key="Register">
        <tr lang="sr"> Регистрација </tr>
      </string>
      <string key="Sign In">
        <tr lang="sr"> Пријава </tr>
      </string>
      <string key="My Account">
        <tr lang="sr"> Мој Налог </tr>
      </string>
      <string key="Find Jobs">
        <tr lang="sr"> Пронађите Посао </tr>
      </string>
      <string key="Post Resumes">
        <tr lang="sr"> Пошаљите Биографију </tr>
      </string>
      <string key="Search Resumes">
        <tr lang="sr"> Претражите Биографије </tr>
      </string>
      <string key="Post Jobs">
        <tr lang="sr"> Објавите Послове </tr>
      </string>
      <string key="Contact">
        <tr lang="sr"> Контакт </tr>
      </string>
      <string key="Choose language">
        <tr lang="sr"> Одаберите Језик </tr>
      </string>
      <string key="Jobs by Category">
        <tr lang="sr"> Послови по Категорији </tr>
      </string>
      <string key="Jobs by City">
        <tr lang="sr"> Послови по Граду </tr>
      </string>
      <string key="Featured Jobs">
        <tr lang="sr"> Истакнути Послови </tr>
      </string>
      <string key="Employers">
        <tr lang="sr"> Запослени </tr>
      </string>
      <string key="Search resumes">
        <tr lang="sr"> Претражите резимее </tr>
      </string>
      <string key="Job Seekers">
        <tr lang="sr"> Кандидат </tr>
      </string>
      <string key="Post resumes">
        <tr lang="sr"> Објави Биографију </tr>
      </string>
      <string key="Find jobs">
        <tr lang="sr"> Пронађи послове </tr>
      </string>
      <string key="RSS Feed">
        <tr lang="sr"> RSS Feed </tr>
      </string>
      <string key="Latest Jobs">
        <tr lang="sr"> Најновији Послови </tr>
      </string>
      <string key="Keep me signed in">
        <tr lang="sr"> Запамти ме </tr>
      </string>
      <string key="Login">
        <tr lang="sr"> Пријава </tr>
      </string>
      <string key="Forgot Your Password?">
        <tr lang="sr"> Заборавили сте Шифру? </tr>
      </string>
      <string key="Registration">
        <tr lang="sr"> Регистрација </tr>
      </string>
      <string key="Salutation First and Last Name">
        <tr lang="sr"> Име и Презиме </tr>
      </string>
      <string key="Email">
        <tr lang="sr"> E-mail </tr>
      </string>
      <string key="Comments">
        <tr lang="sr"> Коментари </tr>
      </string>
      <string key="Submit">
        <tr lang="sr"> Пошаљи </tr>
      </string>
      <string key="Please select the appropriate user group">
        <tr lang="sr"> Молимо вас одаберите прикладну групу </tr>
      </string>
      <string key="Confirm Password">
        <tr lang="sr"> Потврдите Шифру </tr>
      </string>
      <string key="You have successfully registered in our site">
        <tr lang="sr"> Успешно сте се регистровали на наш сајт. </tr>
      </string>
      <string key="Add a New Listing">
        <tr lang="sr"> Додајте Нов Унос </tr>
      </string>
      <string key="You specified wrong username">
        <tr lang="sr"> Унели сте погрешно корисничко име </tr>
      </string>
      <string key="Invalid payment ID is specified">
        <tr lang="sr"> Наведен је погрешан Број рачуна </tr>
      </string>
      <string key="Search">
        <tr lang="sr"> Претрага </tr>
      </string>
      <string key="My Jobs">
        <tr lang="sr"> Моји Послови </tr>
      </string>
      <string key="My Profile">
        <tr lang="sr"> Мој Профил </tr>
      </string>
      <string key="Saved Searches">
        <tr lang="sr"> Снимљене Претраге </tr>
      </string>
      <string key="Saved Listings">
        <tr lang="sr"> Снимљени Листинзи </tr>
      </string>
      <string key="My Notifications">
        <tr lang="sr"> Моја Обавештења </tr>
      </string>
      <string key="Billing History">
        <tr lang="sr"> Историја Плаћања </tr>
      </string>
      <string key="Logout">
        <tr lang="sr"> Одјава </tr>
      </string>
      <string key="My Listings">
        <tr lang="sr"> Моји Листинзи </tr>
      </string>
      <string key="Filter">
        <tr lang="sr"> Филтер </tr>
      </string>
      <string key="unlimited">
        <tr lang="sr"> Неограничено </tr>
      </string>
      <string key="Next">
        <tr lang="sr"> Даље </tr>
      </string>
      <string key="Edit Listing">
        <tr lang="sr"> Измените Унос </tr>
      </string>
      <string key="Upgrade to Featured">
        <tr lang="sr"> Истакни </tr>
      </string>
      <string key="You have already subscribed">
        <tr lang="sr"> Већ сте пријављени </tr>
      </string>
      <string key="No listings found.">
        <tr lang="sr"> Нема пронађених уноса. </tr>
      </string>
      <string key="Listing ID is not defined">
        <tr lang="sr"> Број Уноса није дефинисан </tr>
      </string>
      <string key="Save">
        <tr lang="sr"> Сачувај </tr>
      </string>
      <string key="Image format is not supported">
        <tr lang="sr"> тип слике није подржан </tr>
      </string>
      <string key="You have successfully changed your profile info!">
        <tr lang="sr"> Успешно сте изменили информације на профилу! </tr>
      </string>
      <string key="Delete">
        <tr lang="sr"> Обриши </tr>
      </string>
      <string key="File deleted successfully">
        <tr lang="sr"> Датотека успешно обрисана </tr>
      </string>
      <string key="Back to edit profile">
        <tr lang="sr"> Назад ка измени профила </tr>
      </string>
      <string key="You have not saved any searches yet.">
        <tr lang="sr"> Нисте снимили ни једну претрагу. </tr>
      </string>
      <string key="ID">
        <tr lang="sr"> Број </tr>
      </string>
      <string key="Period">
        <tr lang="sr"> Период </tr>
      </string>
      <string key="State">
        <tr lang="sr"> Државе </tr>
      </string>
      <string key="from">
        <tr lang="sr"> од </tr>
      </string>
      <string key="to">
        <tr lang="sr"> до </tr>
      </string>
      <string key="Date">
        <tr lang="sr"> Датум </tr>
      </string>
      <string key="Description">
        <tr lang="sr"> Опис </tr>
      </string>
      <string key="Amount">
        <tr lang="sr"> Количина </tr>
      </string>
      <string key="Action">
        <tr lang="sr"> Акција </tr>
      </string>
      <string key="Total Amount">
        <tr lang="sr"> Укупан Износ </tr>
      </string>
      <string key="There are no saved listings">
        <tr lang="sr"> Нема сачуваних уноса </tr>
      </string>
      <string key="Notify on Listing Activation">
        <tr lang="sr"> Обавести ме када Унос буде Активиран </tr>
      </string>
      <string key="Modify search">
        <tr lang="sr"> Измени претрагу </tr>
      </string>
      <string key="Saved jobs">
        <tr lang="sr"> Сачувани послови </tr>
      </string>
      <string key="Saved searches">
        <tr lang="sr"> Сачуване претраге </tr>
      </string>
      <string key="Number of jobs per page">
        <tr lang="sr"> Број послова по страни </tr>
      </string>
      <string key="Previous">
        <tr lang="sr"> Назад </tr>
      </string>
      <string key="Save Your Search">
        <tr lang="sr"> Сачувај ову Претрагу </tr>
      </string>
      <string key="Search Name">
        <tr lang="sr"> Тражи по Имену </tr>
      </string>
      <string key="Your search has been saved.">
        <tr lang="sr"> Ваша претрага је сачувана. </tr>
      </string>
      <string key="You may close this window now.">
        <tr lang="sr"> Сада можете затворити овај прозор. </tr>
      </string>
      <string key="Save ad">
        <tr lang="sr"> Сачувај оглас </tr>
      </string>
      <string key="View job details">
        <tr lang="sr"> Погледај детаље о послу </tr>
      </string>
      <string key="Please, Vote!">
        <tr lang="sr"> Молимо Вас да дате своју оцену! </tr>
      </string>
      <string key="Watch a video">
        <tr lang="sr"> Покрени видео </tr>
      </string>
      <string key="Save this Job">
        <tr lang="sr"> Сачувај овај Посао </tr>
      </string>
      <string key="View Saved Jobs">
        <tr lang="sr"> Погледај Сачуване Послове </tr>
      </string>
      <string key="Tell a Friend">
        <tr lang="sr"> Препоручи Пријатељу </tr>
      </string>
      <string key="Print This Ad">
        <tr lang="sr"> Одштампај Оглас </tr>
      </string>
      <string key="Map View">
        <tr lang="sr">  </tr>
      </string>
      <string key="Back to Results">
        <tr lang="sr"> Назад на Резултате </tr>
      </string>
      <string key="Modify Search">
        <tr lang="sr"> Измени Претрагу </tr>
      </string>
      <string key="Rate This Job">
        <tr lang="sr"> Оцени овај Посао </tr>
      </string>
      <string key="User Info">
        <tr lang="sr"> Подаци о Кориснику </tr>
      </string>
      <string key="Video">
        <tr lang="sr"> Видео </tr>
      </string>
      <string key="Apply Now">
        <tr lang="sr"> Пријави се Сада </tr>
      </string>
      <string key="Location">
        <tr lang="sr"> Локација </tr>
      </string>
      <string key="Please wait ...">
        <tr lang="sr"> Молимо вас сачекајте... </tr>
      </string>
      <string key="Add your comment">
        <tr lang="sr"> Унесите ваш коментар </tr>
      </string>
      <string key="Add">
        <tr lang="sr"> Додај </tr>
      </string>
      <string key="View details">
        <tr lang="sr"> Погледај детаље </tr>
      </string>
      <string key="Recommend">
        <tr lang="sr"> Препоручи унос Број </tr>
      </string>
      <string key="Your name">
        <tr lang="sr"> Ваше име </tr>
      </string>
      <string key="Send">
        <tr lang="sr"> Пошаљи </tr>
      </string>
      <string key="Cannot send letter">
        <tr lang="sr"> Писмо није послато </tr>
      </string>
      <string key="Company Info">
        <tr lang="sr"> Назив Компаније </tr>
      </string>
      <string key="You&apos;ve already voted">
        <tr lang="sr"> Већ сте гласали </tr>
      </string>
      <string key="Author">
        <tr lang="sr"> Аутор </tr>
      </string>
      <string key="Your e-mail">
        <tr lang="sr"> Ваша e-mail адреса </tr>
      </string>
      <string key="Attach your resume">
        <tr lang="sr"> Додајте ваш резиме </tr>
      </string>
      <string key="Number of resumes per page">
        <tr lang="sr"> Број Резимеа по страни </tr>
      </string>
      <string key="Add Pictures">
        <tr lang="sr"> Додај Слике </tr>
      </string>
      <string key="is empty">
        <tr lang="sr"> је празан </tr>
      </string>
      <string key="is unknown">
        <tr lang="sr"> је непознат </tr>
      </string>
      <string key="Manage Listing">
        <tr lang="sr"> Управљај Уносом </tr>
      </string>
      <string key="Preview Listing">
        <tr lang="sr"> Прегледајте Унос </tr>
      </string>
      <string key="Add Picture">
        <tr lang="sr"> Додајте Слику </tr>
      </string>
      <string key="Caption">
        <tr lang="sr"> Наслов </tr>
      </string>
      <string key="Thumbnail">
        <tr lang="sr"> Мала Слика (thumbnail) </tr>
      </string>
      <string key="Actions">
        <tr lang="sr"> Акције </tr>
      </string>
      <string key="Are you sure?">
        <tr lang="sr"> Да ли сте сигурни? </tr>
      </string>
      <string key="Edit Picture">
        <tr lang="sr"> Измените слику </tr>
      </string>
      <string key="Picture">
        <tr lang="sr"> Слика </tr>
      </string>
      <string key="Please specify a valid email address.">
        <tr lang="sr"> Молимо вас да унесете исправну интернет адресу (email). </tr>
      </string>
      <string key="Please provide your full name.">
        <tr lang="sr"> Молимо вас унесите Име и Презиме. </tr>
      </string>
      <string key="Please include your comments.">
        <tr lang="sr"> Молимо вас унесите ваш коментар. </tr>
      </string>
      <string key="Thank you very much for your message. We will respond to you as soon as possible.">
        <tr lang="sr"> Много вам хвала на поруци. Ускоро ћемо вам се јавити. </tr>
      </string>
      <string key="Login error">
        <tr lang="sr"> Корисничко име и/или шифра нису исправни </tr>
      </string>
      <string key="Browse by category">
        <tr lang="sr"> Тражи по категорији </tr>
      </string>
      <string key="There are no listings with requested parameters in the system.">
        <tr lang="sr"> Нема уноса по задатом критеријуму у систему. </tr>
      </string>
      <string key="Browse by city">
        <tr lang="sr"> Тражи по граду </tr>
      </string>
      <string key="My Resumes">
        <tr lang="sr"> Мој Резиме </tr>
      </string>
      <string key="Saved Jobs">
        <tr lang="sr"> Сачувани Послови </tr>
      </string>
      <string key="Job Alerts">
        <tr lang="sr"> Обавештења о Послу </tr>
      </string>
      <string key="$select_box_field_distance of Zip $input_text_field_location">
        <tr lang="sr"> $select_box_field_distance Поштанског броја $input_text_field_location </tr>
      </string>
      <string key="$input_text_field_from to $input_text_field_to">
        <tr lang="sr"> $input_text_field_from до $input_text_field_to </tr>
      </string>
      <string key="not confirmed">
        <tr lang="sr"> није потврђено </tr>
      </string>
      <string key="this value is already used in the system">
        <tr lang="sr"> ова вредност је већ употребљена у систему </tr>
      </string>
      <string key="Actions with Selected">
        <tr lang="sr"> Радње са Одабраним </tr>
      </string>
      <string key="Number of listings per page">
        <tr lang="sr"> Број уноса по страни </tr>
      </string>
      <string key="Deactivate">
        <tr lang="sr"> Деактивирај </tr>
      </string>
      <string key="Activate">
        <tr lang="sr"> Активирај </tr>
      </string>
      <string key="Your listing is successfully activated">
        <tr lang="sr"> Ваш унос је успешно активиран </tr>
      </string>
      <string key="Back to My Listings">
        <tr lang="sr"> Назад на Моје Уносе </tr>
      </string>
      <string key="Sort by">
        <tr lang="sr"> Сортирај по </tr>
      </string>
      <string key="Edit">
        <tr lang="sr"> Измени </tr>
      </string>
      <string key="Jobs by $companyName">
        <tr lang="sr"> Послови: $companyName </tr>
      </string>
      <string key="View resume details">
        <tr lang="sr"> Погледај резиме </tr>
      </string>
      <string key="All resumes by this user">
        <tr lang="sr"> Сви резимеи корисника </tr>
      </string>
      <string key="Rate This Resume">
        <tr lang="sr"> Оцени Резиме </tr>
      </string>
      <string key="View Saved Resumes">
        <tr lang="sr"> Погледај сачуване резимее </tr>
      </string>
      <string key="Save this Resume">
        <tr lang="sr"> Сачувај Резиме </tr>
      </string>
      <string key="Resumes by $firstName $lastName">
        <tr lang="sr"> $firstName $lastName, Резимеи </tr>
      </string>
      <string key="is not an integer value">
        <tr lang="sr"> није цео број </tr>
      </string>
      <string key="limit exceeded">
        <tr lang="sr"> прекорачено ограничење </tr>
      </string>
      <string key="You don&apos;t have permissions to access this page.">
        <tr lang="sr"> Немате дозволу за приступ овој страници. </tr>
      </string>
      <string key="Your friend&apos;s name">
        <tr lang="sr"> Име Вашег пријатеља </tr>
      </string>
      <string key="Your friend&apos;s e-mail address">
        <tr lang="sr"> Интернет адреса (e-mail) Вашег пријатеља </tr>
      </string>
      <string key="Dear customer!">
        <tr lang="sr"> Поштовани купци! </tr>
      </string>
      <string key="Please choose from the following payment methods:">
        <tr lang="sr"> Молимо Вас да одаберете неки од следећих начина плаћања: </tr>
      </string>
      <string key="Wire Transfer">
        <tr lang="sr"> Wire Transfer </tr>
      </string>
      <string key="Anonymous User Info">
        <tr lang="sr"> Информације о анонимном кориснику </tr>
      </string>
      <string key="Welcome">
        <tr lang="sr"> Добродошли </tr>
      </string>
      <string key="Please log in to access this page. If you do not have an account, please">
        <tr lang="sr"> Молимо вас да се улогујете да бисте имали приступ овој страни. Уколико не поседујете налог, молимо вас </tr>
      </string>
      <string key="Featured Companies">
        <tr lang="sr"> Истакнуте Компаније </tr>
      </string>
      <string key="Get Resumes by Email">
        <tr lang="sr"> Преузмите резимее путем интернет поште (e-mail) </tr>
      </string>
      <string key="Get Jobs by Email">
        <tr lang="sr"> Преузмите послове путем интернет поште (e-mail) </tr>
      </string>
      <string key="Confirm E-mail">
        <tr lang="sr"> Потврдите интернет адресу (е-mail) </tr>
      </string>
      <string key="Reload Image">
        <tr lang="sr"> Замени Слику </tr>
      </string>
      <string key="Accept terms of use">
        <tr lang="sr"> Прихватам услове коришћења </tr>
      </string>
      <string key="Read terms of use">
        <tr lang="sr"> Прочитајте услове коришћења </tr>
      </string>
      <string key="Resume Alerts">
        <tr lang="sr"> Обавештења о Биографији </tr>
      </string>
      <string key="Application Tracking">
        <tr lang="sr"> Апликација за праћење </tr>
      </string>
      <string key="Resume Alert Name">
        <tr lang="sr"> Назив Обавештења о Биографији </tr>
      </string>
      <string key="Add new resume alert">
        <tr lang="sr"> Додај ново обавештење о Биографији </tr>
      </string>
      <string key="Disable">
        <tr lang="sr"> Онемогући </tr>
      </string>
      <string key="Preview Search Results">
        <tr lang="sr"> Прегледај резултате претраге </tr>
      </string>
      <string key="Add resume alert">
        <tr lang="sr"> Додај обавештење о резимеу </tr>
      </string>
      <string key="Alert Name">
        <tr lang="sr"> Назив обавештења </tr>
      </string>
      <string key="Date Applied">
        <tr lang="sr"> Додај Датум </tr>
      </string>
      <string key="Status">
        <tr lang="sr"> Стање </tr>
      </string>
      <string key="Attached Resume">
        <tr lang="sr"> У прилогу додатак </tr>
      </string>
      <string key="Applicant’s Name">
        <tr lang="sr"> Назив подносиоца захтева </tr>
      </string>
      <string key="View Attached File">
        <tr lang="sr"> Погледај приложен фајл </tr>
      </string>
      <string key="Job Search Results">
        <tr lang="sr"> Резултати претаге послова </tr>
      </string>
      <string key="Company Profile">
        <tr lang="sr"> Профил компаније </tr>
      </string>
      <string key="here">
        <tr lang="sr"> овде </tr>
      </string>
      <string key="to add a new listing.">
        <tr lang="sr"> Да додате нов унос. </tr>
      </string>
      <string key="Fields marked with an asterisk (">
        <tr lang="sr"> Поља означена звездицом ( </tr>
      </string>
      <string key=") are mandatory">
        <tr lang="sr"> ) су обавезна </tr>
      </string>
      <string key="Please log in to place a listing. If you do not have an account, please">
        <tr lang="sr"> Молимо Вас да се пријавите да бисте били у могућности да направите нов унос. Уколико немате налог, молимо Вас </tr>
      </string>
      <string key="within $radius $radius_search_unit of $location">
        <tr lang="sr"> У Пречнику од $radius $radius_search_unit  $location </tr>
      </string>
      <string key="Apply to job">
        <tr lang="sr"> Пријавите се за посао </tr>
      </string>
      <string key="Cover letter (optional)">
        <tr lang="sr"> Пропратно писмо (није обавезно) </tr>
      </string>
      <string key="You applied successfully">
        <tr lang="sr"> Успештно сте се пријавили </tr>
      </string>
      <string key="Please log in to place a new posting. If you do not have an account, please">
        <tr lang="sr"> Молимо Вас да се пријавите да бисте били у могућности да направите нов унос. Уколико немате налог, молимо Вас </tr>
      </string>
      <string key="Register.">
        <tr lang="sr"> Регистрација. </tr>
      </string>
      <string key="Search by Company">
        <tr lang="sr"> Претрага по Компанији </tr>
      </string>
      <string key="Clone">
        <tr lang="sr"> Клонирај </tr>
      </string>
      <string key="My Job Preview">
        <tr lang="sr"> Преглед Посла </tr>
      </string>
      <string key="Click to select">
        <tr lang="sr"> Кликни да би одабрао </tr>
      </string>
      <string key="Redirect to this URL">
        <tr lang="sr"> Преусмери на овау интернет страну (УРЛ) </tr>
      </string>
      <string key="Use the following format:">
        <tr lang="sr"> Користи следећи формат: </tr>
      </string>
      <string key="Your changes were successfully saved">
        <tr lang="sr"> Ваше измене су успешно сачуване </tr>
      </string>
      <string key="Manage Pictures">
        <tr lang="sr"> Управљај Сликама </tr>
      </string>
      <string key="Clone Job">
        <tr lang="sr"> Дуплирај Посао </tr>
      </string>
      <string key="Company">
        <tr lang="sr"> Компанија </tr>
      </string>
      <string key="My Applications">
        <tr lang="sr"> Моје Пријаве </tr>
      </string>
      <string key="Select your resume">
        <tr lang="sr"> Одаберите Ваш резиме </tr>
      </string>
      <string key="My Postings">
        <tr lang="sr"> Моји Послови </tr>
      </string>
      <string key="Private messages">
        <tr lang="sr"> Приватне поруке </tr>
      </string>
      <string key="Inbox">
        <tr lang="sr"> Примљено </tr>
      </string>
      <string key="Outbox">
        <tr lang="sr"> Послате Поруке </tr>
      </string>
      <string key="Edit Saved Search">
        <tr lang="sr"> Измени Сачувану Претрагу </tr>
      </string>
      <string key="Saved Searches Name">
        <tr lang="sr"> Назив Сачуване Претраге </tr>
      </string>
      <string key="Cover Letter">
        <tr lang="sr"> Пропратно писмо </tr>
      </string>
      <string key="Compose Message">
        <tr lang="sr"> Састави Нову Поруку </tr>
      </string>
      <string key="From">
        <tr lang="sr"> Од </tr>
      </string>
      <string key="Subject">
        <tr lang="sr"> Тема </tr>
      </string>
      <string key="To">
        <tr lang="sr"> Ка </tr>
      </string>
      <string key="Message to">
        <tr lang="sr"> Поруку прима </tr>
      </string>
      <string key="Message">
        <tr lang="sr"> Порука </tr>
      </string>
      <string key="Save to outbox">
        <tr lang="sr"> Сачувај у послатим порукама </tr>
      </string>
      <string key="Send private message">
        <tr lang="sr"> Пошаљите приватну поруку </tr>
      </string>
      <string key="You&apos;re not allowed to open this page">
        <tr lang="sr"> Немате дозволу да видите садржај ове странице </tr>
      </string>
      <string key="Resume has been saved">
        <tr lang="sr"> Резиме је сачуван </tr>
      </string>
      <string key="Send applications online via web site">
        <tr lang="sr"> Шаљите пријаве путем веб сајта </tr>
      </string>
      <string key="Job Alert Name">
        <tr lang="sr"> Назив Обавештења о послу </tr>
      </string>
      <string key="Add new job alert">
        <tr lang="sr"> Додај ново обавештење о послу </tr>
      </string>
      <string key="Jobs Applied">
        <tr lang="sr"> Аплицирани послови </tr>
      </string>
      <string key="Company Search Results">
        <tr lang="sr"> Резултат претраге компаније </tr>
      </string>
      <string key="Mark as Read">
        <tr lang="sr"> Прочитано </tr>
      </string>
      <string key="Message from">
        <tr lang="sr"> Порука од </tr>
      </string>
      <string key="Read Private Message">
        <tr lang="sr"> Прочитајте приватну поруку </tr>
      </string>
      <string key="Reply">
        <tr lang="sr"> Одговори </tr>
      </string>
      <string key="Approve selected">
        <tr lang="sr"> Одобри одабрано </tr>
      </string>
      <string key="Reject selected">
        <tr lang="sr"> Одби одабрано </tr>
      </string>
      <string key="Pending">
        <tr lang="sr"> У току </tr>
      </string>
      <string key="Approved">
        <tr lang="sr"> Одобрено </tr>
      </string>
      <string key="Rejected">
        <tr lang="sr"> Одбијено </tr>
      </string>
      <string key="Select Job Posting">
        <tr lang="sr"> Одаберите Посао </tr>
      </string>
      <string key="All Jobs">
        <tr lang="sr"> Сви послови </tr>
      </string>
      <string key="Delete profile">
        <tr lang="sr"> Обришите профил </tr>
      </string>
      <string key="Back">
        <tr lang="sr"> Назад </tr>
      </string>
      <string key="Enable">
        <tr lang="sr"> Омогући </tr>
      </string>
      <string key="Email frequency">
        <tr lang="sr"> Учесталост електронске поште(и-мејл) </tr>
      </string>
      <string key="Subscription date">
        <tr lang="sr"> Датум пријављивања </tr>
      </string>
      <string key="Subscription expiration date">
        <tr lang="sr"> Датум истицања претплате </tr>
      </string>
      <string key="Not Available Anymore">
        <tr lang="sr"> Више није доступно </tr>
      </string>
      <string key="home">
        <tr lang="sr"> почетак </tr>
      </string>
      <string key="Search job title only">
        <tr lang="sr"> Претражите само наслов посла </tr>
      </string>
      <string key="Edit notes">
        <tr lang="sr"> Измени белешке </tr>
      </string>
      <string key="Add notes">
        <tr lang="sr"> Додај белешку </tr>
      </string>
      <string key="Close">
        <tr lang="sr"> Затвори </tr>
      </string>
      <string key="My notes">
        <tr lang="sr"> Моје белешке </tr>
      </string>
      <string key="Search resume title only">
        <tr lang="sr"> Претражите само наслов резимеа </tr>
      </string>
      <string key="Search by title">
        <tr lang="sr"> Претражите по наслову </tr>
      </string>
      <string key="Match exact phrase">
        <tr lang="sr"> Пронађи фразу </tr>
      </string>
      <string key="Match all words">
        <tr lang="sr"> Пронађи све речи </tr>
      </string>
      <string key="Match any words">
        <tr lang="sr"> Пронађи било коју реч </tr>
      </string>
      <string key="Boolean">
        <tr lang="sr"> Булова </tr>
      </string>
      <string key="Terms of use">
        <tr lang="sr"> Услови коришћења </tr>
      </string>
      <string key="Test URL">
        <tr lang="sr"> Проверите веб адресу (УРЛ) </tr>
      </string>
      <string key="Go Search">
        <tr lang="sr"> Започни претрагу </tr>
      </string>
      <string key="Total">
        <tr lang="sr"> Укупно </tr>
      </string>
      <string key="Boolean search description">
        <tr lang="sr"> Булова претрага описа </tr>
      </string>
      <string key="Employers List">
        <tr lang="sr"> Списак послодаваца </tr>
      </string>
      <string key="Selected Employers">
        <tr lang="sr"> Одабрани послодавци </tr>
      </string>
      <string key="* Use CTRL key to select two or more employers">
        <tr lang="sr"> * Користите тастер ЦТРЛ (CTRL) да одаберете два или више послодавца </tr>
      </string>
      <string key="Loading">
        <tr lang="sr"> Учитавам </tr>
      </string>
      <string key="Currency">
        <tr lang="sr"> Валута </tr>
      </string>
      <string key="Deselect all">
        <tr lang="sr"> Поништите све </tr>
      </string>
      <string key="Please choose Excel or csv file">
        <tr lang="sr"> Молимо вас да одаберете &quot;Excel&quot; или &quot;csv&quot; фајл </tr>
      </string>
      <string key="Your recurring subscription to the &quot;$cancelMembershipPlanName&quot; plan has been canceled.">